gucoordinates: tests/camera_pivot_fakes.h File Reference
camera_pivot_fakes.h File Reference
#include "fff.h"
#include "../camera_pivot.h"
Classes
struct gu_camera_pivot_equals_Fake
Macros
#define CAMERA_PIVOT_FAKES(FAKE) FAKE(gu_camera_pivot_equals)
Typedefs
typedef struct gu_camera_pivot_equals_Fake gu_camera_pivot_equals_Fake
Functions
void gu_camera_pivot_equals_reset (void)
bool gu_camera_pivot_equals (const gu_camera_pivot arg0, const gu_camera_pivot arg1, const double arg2)
Variables
gu_camera_pivot_equals_Fake gu_camera_pivot_equals_fake
Macro Definition Documentation
CAMERA_PIVOT_FAKES
#define CAMERA_PIVOT_FAKES (FAKE) FAKE(gu_camera_pivot_equals)
Definition at line 69 of file camera_pivot_fakes.h.
Typedef Documentation
gu_camera_pivot_equals_Fake
typedef struct gu_camera_pivot_equals_Fake gu_camera_pivot_equals_Fake
Function Documentation
gu_camera_pivot_equals()
bool gu_camera_pivot_equals (const gu_camera_pivot arg0, const gu_camera_pivot arg1, const double arg2)
Definition at line 64 of file camera_pivot.c.
References gu_camera_pivot::cameras, gu_camera_equals(), gu_camera_pivot::height, gu_camera_pivot::numCameras, gu_camera_pivot::pitch, and gu_camera_pivot::yaw.
Referenced by GU::CameraPivot::operator==(), and CGTEST::TEST_F().
gu_camera_pivot_equals_reset()
void gu_camera_pivot_equals_reset (void)
Definition at line 64 of file camera_pivot_fakes.c.
Variable Documentation
gu_camera_pivot_equals_fake
gu_camera_pivot_equals_Fake gu_camera_pivot_equals_fake extern
Definition at line 64 of file camera_pivot_fakes.c.