gucoordinates: tests/camera_coordinate_fakes.h File Reference
camera_coordinate_fakes.h File Reference
#include "fff.h"
#include "../camera_coordinate.h"
Classes
struct gu_camera_coordinate_equals_Fake
struct gu_camera_coordinate_x_lower_bound_Fake
struct gu_camera_coordinate_y_lower_bound_Fake
struct gu_camera_coordinate_x_upper_bound_Fake
struct gu_camera_coordinate_y_upper_bound_Fake
Macros
#define CAMERA_COORDINATE_FAKES(FAKE)
Typedefs
typedef struct gu_camera_coordinate_equals_Fake gu_camera_coordinate_equals_Fake
typedef struct gu_camera_coordinate_x_lower_bound_Fake gu_camera_coordinate_x_lower_bound_Fake
typedef struct gu_camera_coordinate_y_lower_bound_Fake gu_camera_coordinate_y_lower_bound_Fake
typedef struct gu_camera_coordinate_x_upper_bound_Fake gu_camera_coordinate_x_upper_bound_Fake
typedef struct gu_camera_coordinate_y_upper_bound_Fake gu_camera_coordinate_y_upper_bound_Fake
Functions
void gu_camera_coordinate_equals_reset (void)
bool gu_camera_coordinate_equals (const gu_camera_coordinate arg0, const gu_camera_coordinate arg1)
void gu_camera_coordinate_x_lower_bound_reset (void)
pixels_t gu_camera_coordinate_x_lower_bound (const gu_camera_coordinate arg0)
void gu_camera_coordinate_y_lower_bound_reset (void)
pixels_t gu_camera_coordinate_y_lower_bound (const gu_camera_coordinate arg0)
void gu_camera_coordinate_x_upper_bound_reset (void)
pixels_t gu_camera_coordinate_x_upper_bound (const gu_camera_coordinate arg0)
void gu_camera_coordinate_y_upper_bound_reset (void)
pixels_t gu_camera_coordinate_y_upper_bound (const gu_camera_coordinate arg0)
Variables
gu_camera_coordinate_equals_Fake gu_camera_coordinate_equals_fake
gu_camera_coordinate_x_lower_bound_Fake gu_camera_coordinate_x_lower_bound_fake
gu_camera_coordinate_y_lower_bound_Fake gu_camera_coordinate_y_lower_bound_fake
gu_camera_coordinate_x_upper_bound_Fake gu_camera_coordinate_x_upper_bound_fake
gu_camera_coordinate_y_upper_bound_Fake gu_camera_coordinate_y_upper_bound_fake
Macro Definition Documentation
CAMERA_COORDINATE_FAKES
#define CAMERA_COORDINATE_FAKES (FAKE)
Value:
    FAKE(gu_camera_coordinate_equals) \
    FAKE(gu_camera_coordinate_x_lower_bound) \
    FAKE(gu_camera_coordinate_y_lower_bound) \
    FAKE(gu_camera_coordinate_x_upper_bound) \
    FAKE(gu_camera_coordinate_y_upper_bound)
Definition at line 69 of file camera_coordinate_fakes.h.
Typedef Documentation
gu_camera_coordinate_equals_Fake
typedef struct gu_camera_coordinate_equals_Fake gu_camera_coordinate_equals_Fake
gu_camera_coordinate_x_lower_bound_Fake
typedef struct gu_camera_coordinate_x_lower_bound_Fake gu_camera_coordinate_x_lower_bound_Fake
gu_camera_coordinate_x_upper_bound_Fake
typedef struct gu_camera_coordinate_x_upper_bound_Fake gu_camera_coordinate_x_upper_bound_Fake
gu_camera_coordinate_y_lower_bound_Fake
typedef struct gu_camera_coordinate_y_lower_bound_Fake gu_camera_coordinate_y_lower_bound_Fake
gu_camera_coordinate_y_upper_bound_Fake
typedef struct gu_camera_coordinate_y_upper_bound_Fake gu_camera_coordinate_y_upper_bound_Fake
Function Documentation
gu_camera_coordinate_equals()
bool gu_camera_coordinate_equals (const gu_camera_coordinate arg0, const gu_camera_coordinate arg1)
Definition at line 61 of file camera_coordinate.c.
References gu_camera_coordinate::res_height, gu_camera_coordinate::res_width, gu_camera_coordinate::x, and gu_camera_coordinate::y.
Referenced by gu_optional_camera_coordinate_equals(), GU::CameraCoordinate::operator==(), and CGTEST::TEST_F().
gu_camera_coordinate_equals_reset()
void gu_camera_coordinate_equals_reset (void)
Definition at line 63 of file camera_coordinate_fakes.c.
gu_camera_coordinate_x_lower_bound()
pixels_t gu_camera_coordinate_x_lower_bound (const gu_camera_coordinate arg0)
Definition at line 69 of file camera_coordinate.c.
Referenced by GU::CameraCoordinate::xLowerBound().
gu_camera_coordinate_x_lower_bound_reset()
void gu_camera_coordinate_x_lower_bound_reset (void)
Definition at line 64 of file camera_coordinate_fakes.c.
gu_camera_coordinate_x_upper_bound()
pixels_t gu_camera_coordinate_x_upper_bound (const gu_camera_coordinate arg0)
Definition at line 81 of file camera_coordinate.c.
References gu_camera_coordinate::res_width.
Referenced by GU::CameraCoordinate::xUpperBound().
gu_camera_coordinate_x_upper_bound_reset()
void gu_camera_coordinate_x_upper_bound_reset (void)
Definition at line 66 of file camera_coordinate_fakes.c.
gu_camera_coordinate_y_lower_bound()
pixels_t gu_camera_coordinate_y_lower_bound (const gu_camera_coordinate arg0)
Definition at line 75 of file camera_coordinate.c.
Referenced by GU::CameraCoordinate::yLowerBound().
gu_camera_coordinate_y_lower_bound_reset()
void gu_camera_coordinate_y_lower_bound_reset (void)
Definition at line 65 of file camera_coordinate_fakes.c.
gu_camera_coordinate_y_upper_bound()
pixels_t gu_camera_coordinate_y_upper_bound (const gu_camera_coordinate arg0)
Definition at line 86 of file camera_coordinate.c.
References gu_camera_coordinate::res_height.
Referenced by GU::CameraCoordinate::yUpperBound().
gu_camera_coordinate_y_upper_bound_reset()
void gu_camera_coordinate_y_upper_bound_reset (void)
Definition at line 67 of file camera_coordinate_fakes.c.
Variable Documentation
gu_camera_coordinate_equals_fake
gu_camera_coordinate_equals_Fake gu_camera_coordinate_equals_fake extern
Definition at line 63 of file camera_coordinate_fakes.c.
gu_camera_coordinate_x_lower_bound_fake
gu_camera_coordinate_x_lower_bound_Fake gu_camera_coordinate_x_lower_bound_fake extern
Definition at line 64 of file camera_coordinate_fakes.c.
gu_camera_coordinate_x_upper_bound_fake
gu_camera_coordinate_x_upper_bound_Fake gu_camera_coordinate_x_upper_bound_fake extern
Definition at line 66 of file camera_coordinate_fakes.c.
gu_camera_coordinate_y_lower_bound_fake
gu_camera_coordinate_y_lower_bound_Fake gu_camera_coordinate_y_lower_bound_fake extern
Definition at line 65 of file camera_coordinate_fakes.c.
gu_camera_coordinate_y_upper_bound_fake
gu_camera_coordinate_y_upper_bound_Fake gu_camera_coordinate_y_upper_bound_fake extern
Definition at line 67 of file camera_coordinate_fakes.c.