gucoordinates: camera_coordinate.c File Reference
camera_coordinate.c File Reference
#include "camera_coordinate.h"
Functions
bool gu_camera_coordinate_equals (const gu_camera_coordinate lhs, const gu_camera_coordinate rhs)
pixels_t gu_camera_coordinate_x_lower_bound (const gu_camera_coordinate coord)
pixels_t gu_camera_coordinate_y_lower_bound (const gu_camera_coordinate coord)
pixels_t gu_camera_coordinate_x_upper_bound (const gu_camera_coordinate coord)
pixels_t gu_camera_coordinate_y_upper_bound (const gu_camera_coordinate coord)
Function Documentation
gu_camera_coordinate_equals()
bool gu_camera_coordinate_equals (const gu_camera_coordinate lhs, const gu_camera_coordinate rhs)
Definition at line 61 of file camera_coordinate.c.
References gu_camera_coordinate::res_height, gu_camera_coordinate::res_width, gu_camera_coordinate::x, and gu_camera_coordinate::y.
Referenced by gu_optional_camera_coordinate_equals(), GU::CameraCoordinate::operator==(), and CGTEST::TEST_F().
gu_camera_coordinate_x_lower_bound()
pixels_t gu_camera_coordinate_x_lower_bound (const gu_camera_coordinate coord)
Definition at line 69 of file camera_coordinate.c.
Referenced by GU::CameraCoordinate::xLowerBound().
gu_camera_coordinate_x_upper_bound()
pixels_t gu_camera_coordinate_x_upper_bound (const gu_camera_coordinate coord)
Definition at line 81 of file camera_coordinate.c.
References gu_camera_coordinate::res_width.
Referenced by GU::CameraCoordinate::xUpperBound().
gu_camera_coordinate_y_lower_bound()
pixels_t gu_camera_coordinate_y_lower_bound (const gu_camera_coordinate coord)
Definition at line 75 of file camera_coordinate.c.
Referenced by GU::CameraCoordinate::yLowerBound().
gu_camera_coordinate_y_upper_bound()
pixels_t gu_camera_coordinate_y_upper_bound (const gu_camera_coordinate coord)
Definition at line 86 of file camera_coordinate.c.
References gu_camera_coordinate::res_height.
Referenced by GU::CameraCoordinate::yUpperBound().