gucoordinates: camera_pivot.c File Reference
camera_pivot.c File Reference
#include "camera_pivot.h"
#include <stdbool.h>
#include <math.h>
Functions
bool gu_camera_pivot_equals (const gu_camera_pivot lhs, const gu_camera_pivot rhs, const double tolerance)
centimetres_d gu_camera_pivot_calculate_camera_height (const gu_camera_pivot camera_pivot, const int cameraOffset)
bool gu_camera_pivot_object_on_ground (const gu_camera_pivot camera_pivot, const int cameraOffset, const gu_percent_coordinate coord)
bool gu_camera_pivot_can_see_object (const gu_camera_pivot camera_pivot, const int cameraOffset, const gu_relative_coordinate coord)
Function Documentation
gu_camera_pivot_calculate_camera_height()
centimetres_d gu_camera_pivot_calculate_camera_height (const gu_camera_pivot camera_pivot, const int cameraOffset)
Definition at line 83 of file camera_pivot.c.
References gu_camera_pivot::cameras, gu_camera::centerOffset, gu_camera::height, gu_camera_pivot::height, and gu_camera_pivot::pitch.
Referenced by gu_camera_pivot_can_see_object(), pct_coord_to_rr_coord(), and rr_coord_to_pct_coord().
gu_camera_pivot_can_see_object()
bool gu_camera_pivot_can_see_object (const gu_camera_pivot camera_pivot, const int cameraOffset, const gu_relative_coordinate coord)
Definition at line 101 of file camera_pivot.c.
References gu_camera_pivot::cameras, gu_camera::centerOffset, gu_relative_coordinate::direction, gu_relative_coordinate::distance, gu_camera_pivot_calculate_camera_height(), gu_camera::hFov, gu_camera_pivot::pitch, gu_camera::vDirection, gu_camera::vFov, and gu_camera_pivot::yaw.
gu_camera_pivot_equals()
bool gu_camera_pivot_equals (const gu_camera_pivot lhs, const gu_camera_pivot rhs, const double tolerance)
Definition at line 64 of file camera_pivot.c.
References gu_camera_pivot::cameras, gu_camera_equals(), gu_camera_pivot::height, gu_camera_pivot::numCameras, gu_camera_pivot::pitch, and gu_camera_pivot::yaw.
Referenced by GU::CameraPivot::operator==(), and CGTEST::TEST_F().
gu_camera_pivot_object_on_ground()
bool gu_camera_pivot_object_on_ground (const gu_camera_pivot camera_pivot, const int cameraOffset, const gu_percent_coordinate coord)
Definition at line 94 of file camera_pivot.c.
References gu_camera_pivot::cameras, gu_camera_pivot::pitch, gu_camera::vDirection, gu_camera::vFov, and gu_percent_coordinate::y.