gucoordinates: CGTEST::CameraCoordinateCPPTests Class Reference
CGTEST::CameraCoordinateCPPTests Class Reference
Protected Member Functions
GU::CameraCoordinate initial ()
GU::CameraCoordinate empty ()
void change (GU::CameraCoordinate &obj)
void cchange (gu_camera_coordinate &obj)
gu_camera_coordinate cempty ()
Protected Member Functions inherited from CGTEST::GUWrapperTests< GU::CameraCoordinate, gu_camera_coordinate >
void c_convertible_test ()
Protected Member Functions inherited from CGTEST::GUCoordinatesTests< Class >
virtual void SetUp ()
virtual void TearDown ()
void camera_equal (const gu_camera_coordinate lhs, const gu_camera_coordinate rhs)
void pixel_equal (const gu_pixel_coordinate lhs, const gu_pixel_coordinate rhs)
void percent_equal (const gu_percent_coordinate lhs, const gu_percent_coordinate rhs)
void percent_near (const gu_percent_coordinate lhs, const gu_percent_coordinate rhs)
virtual void SetUp ()
virtual void TearDown ()
virtual void preamble ()
virtual void change (Class &)
void ro3_test ()
void ro5_test ()
bool near (const double lhs, const double rhs) const
void assert_near (const double lhs, const double rhs, const double tolerance) const
void equals (const GU::CameraCoordinate lhs, const GU::CameraCoordinate rhs)
void nequals (const GU::CameraCoordinate lhs, const GU::CameraCoordinate rhs)
void equals (const GU::Camera lhs, const GU::Camera rhs)
void nequals (const GU::Camera lhs, const GU::Camera rhs)
void equals (const GU::PixelCoordinate lhs, const GU::PixelCoordinate rhs)
void nequals (const GU::PixelCoordinate lhs, const GU::PixelCoordinate rhs)
void equals (const GU::PercentCoordinate lhs, const GU::PercentCoordinate rhs)
void nequals (const GU::PercentCoordinate lhs, const GU::PercentCoordinate rhs)
void equals (const GU::RelativeCoordinate lhs, const GU::RelativeCoordinate rhs)
void nequals (const GU::RelativeCoordinate lhs, const GU::RelativeCoordinate rhs)
void equals (const GU::CartesianCoordinate lhs, const GU::CartesianCoordinate rhs)
void nequals (const GU::CartesianCoordinate lhs, const GU::CartesianCoordinate rhs)
void equals (const GU::FieldCoordinate lhs, const GU::FieldCoordinate rhs)
void nequals (const GU::FieldCoordinate lhs, const GU::FieldCoordinate rhs)
void equals (const GU::CameraPivot lhs, const GU::CameraPivot rhs)
void nequals (const GU::CameraPivot lhs, const GU::CameraPivot rhs)
void equals (const GU::OptionalCameraCoordinate lhs, const GU::OptionalCameraCoordinate rhs)
void nequals (const GU::OptionalCameraCoordinate lhs, const GU::OptionalCameraCoordinate rhs)
void equals (const GU::OptionalPixelCoordinate lhs, const GU::OptionalPixelCoordinate rhs)
void nequals (const GU::OptionalPixelCoordinate lhs, const GU::OptionalPixelCoordinate rhs)
void equals (const GU::OptionalPercentCoordinate lhs, const GU::OptionalPercentCoordinate rhs)
void nequals (const GU::OptionalPercentCoordinate lhs, const GU::OptionalPercentCoordinate rhs)
void equals (const GU::OptionalRelativeCoordinate lhs, const GU::OptionalRelativeCoordinate rhs)
void nequals (const GU::OptionalRelativeCoordinate lhs, const GU::OptionalRelativeCoordinate rhs)
void equals (const GU::OptionalCartesianCoordinate lhs, const GU::OptionalCartesianCoordinate rhs)
void nequals (const GU::OptionalCartesianCoordinate lhs, const GU::OptionalCartesianCoordinate rhs)
void equals (const GU::OptionalFieldCoordinate lhs, const GU::OptionalFieldCoordinate rhs)
void nequals (const GU::OptionalFieldCoordinate lhs, const GU::OptionalFieldCoordinate rhs)
Additional Inherited Members
Protected Attributes inherited from CGTEST::GUCoordinatesTests< Class >
GU::CameraPivot nao
GU::Camera topCamera
GU::Camera bottomCamera
Detailed Description
Definition at line 63 of file CameraCoordinateTests.cc.
Member Function Documentation
cchange()
void CGTEST::CameraCoordinateCPPTests::cchange (gu_camera_coordinate & obj) inline protected virtual
Implements CGTEST::GUWrapperTests< GU::CameraCoordinate, gu_camera_coordinate >.
Definition at line 82 of file CameraCoordinateTests.cc.
References gu_camera_coordinate::res_height, gu_camera_coordinate::res_width, gu_camera_coordinate::x, and gu_camera_coordinate::y.
cempty()
gu_camera_coordinate CGTEST::CameraCoordinateCPPTests::cempty () inline protected virtual
Implements CGTEST::GUWrapperTests< GU::CameraCoordinate, gu_camera_coordinate >.
Definition at line 90 of file CameraCoordinateTests.cc.
References empty().
change()
void CGTEST::CameraCoordinateCPPTests::change (GU::CameraCoordinate & obj) inline protected
Definition at line 77 of file CameraCoordinateTests.cc.
References GU::CameraCoordinate::set_x().
empty()
GU::CameraCoordinate CGTEST::CameraCoordinateCPPTests::empty () inline protected virtual
Implements CGTEST::GUCoordinatesTests< Class >.
Definition at line 72 of file CameraCoordinateTests.cc.
Referenced by cempty().
initial()
GU::CameraCoordinate CGTEST::CameraCoordinateCPPTests::initial () inline protected virtual
Implements CGTEST::GUCoordinatesTests< Class >.
Definition at line 67 of file CameraCoordinateTests.cc.
The documentation for this class was generated from the following file:
tests/CameraCoordinateTests.cc