gucoordinates: CGTEST::CameraPivotCPPTests Class Reference
CGTEST::CameraPivotCPPTests Class Reference
Protected Member Functions
void preamble ()
GU::CameraPivot initial ()
GU::CameraPivot empty ()
void change (GU::CameraPivot &obj)
void cchange (gu_camera_pivot &obj)
gu_camera_pivot cempty ()
Protected Member Functions inherited from CGTEST::GUWrapperTests< GU::CameraPivot, gu_camera_pivot >
void c_convertible_test ()
Protected Member Functions inherited from CGTEST::GUCoordinatesTests< Class >
virtual void SetUp ()
virtual void TearDown ()
void camera_equal (const gu_camera_coordinate lhs, const gu_camera_coordinate rhs)
void pixel_equal (const gu_pixel_coordinate lhs, const gu_pixel_coordinate rhs)
void percent_equal (const gu_percent_coordinate lhs, const gu_percent_coordinate rhs)
void percent_near (const gu_percent_coordinate lhs, const gu_percent_coordinate rhs)
virtual void SetUp ()
virtual void TearDown ()
virtual void change (Class &)
void ro3_test ()
void ro5_test ()
bool near (const double lhs, const double rhs) const
void assert_near (const double lhs, const double rhs, const double tolerance) const
void equals (const GU::CameraCoordinate lhs, const GU::CameraCoordinate rhs)
void nequals (const GU::CameraCoordinate lhs, const GU::CameraCoordinate rhs)
void equals (const GU::Camera lhs, const GU::Camera rhs)
void nequals (const GU::Camera lhs, const GU::Camera rhs)
void equals (const GU::PixelCoordinate lhs, const GU::PixelCoordinate rhs)
void nequals (const GU::PixelCoordinate lhs, const GU::PixelCoordinate rhs)
void equals (const GU::PercentCoordinate lhs, const GU::PercentCoordinate rhs)
void nequals (const GU::PercentCoordinate lhs, const GU::PercentCoordinate rhs)
void equals (const GU::RelativeCoordinate lhs, const GU::RelativeCoordinate rhs)
void nequals (const GU::RelativeCoordinate lhs, const GU::RelativeCoordinate rhs)
void equals (const GU::CartesianCoordinate lhs, const GU::CartesianCoordinate rhs)
void nequals (const GU::CartesianCoordinate lhs, const GU::CartesianCoordinate rhs)
void equals (const GU::FieldCoordinate lhs, const GU::FieldCoordinate rhs)
void nequals (const GU::FieldCoordinate lhs, const GU::FieldCoordinate rhs)
void equals (const GU::CameraPivot lhs, const GU::CameraPivot rhs)
void nequals (const GU::CameraPivot lhs, const GU::CameraPivot rhs)
void equals (const GU::OptionalCameraCoordinate lhs, const GU::OptionalCameraCoordinate rhs)
void nequals (const GU::OptionalCameraCoordinate lhs, const GU::OptionalCameraCoordinate rhs)
void equals (const GU::OptionalPixelCoordinate lhs, const GU::OptionalPixelCoordinate rhs)
void nequals (const GU::OptionalPixelCoordinate lhs, const GU::OptionalPixelCoordinate rhs)
void equals (const GU::OptionalPercentCoordinate lhs, const GU::OptionalPercentCoordinate rhs)
void nequals (const GU::OptionalPercentCoordinate lhs, const GU::OptionalPercentCoordinate rhs)
void equals (const GU::OptionalRelativeCoordinate lhs, const GU::OptionalRelativeCoordinate rhs)
void nequals (const GU::OptionalRelativeCoordinate lhs, const GU::OptionalRelativeCoordinate rhs)
void equals (const GU::OptionalCartesianCoordinate lhs, const GU::OptionalCartesianCoordinate rhs)
void nequals (const GU::OptionalCartesianCoordinate lhs, const GU::OptionalCartesianCoordinate rhs)
void equals (const GU::OptionalFieldCoordinate lhs, const GU::OptionalFieldCoordinate rhs)
void nequals (const GU::OptionalFieldCoordinate lhs, const GU::OptionalFieldCoordinate rhs)
Protected Attributes
gu_camera cameras [2]
gu_camera_pivot empty_strct
Protected Attributes inherited from CGTEST::GUCoordinatesTests< Class >
GU::CameraPivot nao
GU::Camera topCamera
GU::Camera bottomCamera
Detailed Description
Definition at line 63 of file CameraPivotTests.cc.
Member Function Documentation
cchange()
void CGTEST::CameraPivotCPPTests::cchange (gu_camera_pivot & obj) inline protected virtual
Implements CGTEST::GUWrapperTests< GU::CameraPivot, gu_camera_pivot >.
Definition at line 104 of file CameraPivotTests.cc.
References gu_camera_pivot::cameras, cameras, GU_CAMERA_PIVOT_NUM_CAMERAS, gu_camera_pivot::height, gu_camera_pivot::numCameras, gu_camera_pivot::pitch, and gu_camera_pivot::yaw.
cempty()
gu_camera_pivot CGTEST::CameraPivotCPPTests::cempty () inline protected virtual
Implements CGTEST::GUWrapperTests< GU::CameraPivot, gu_camera_pivot >.
Definition at line 113 of file CameraPivotTests.cc.
References empty().
change()
void CGTEST::CameraPivotCPPTests::change (GU::CameraPivot & obj) inline protected
Definition at line 99 of file CameraPivotTests.cc.
References GU::CameraPivot::set_pitch().
empty()
GU::CameraPivot CGTEST::CameraPivotCPPTests::empty () inline protected virtual
Implements CGTEST::GUCoordinatesTests< Class >.
Definition at line 94 of file CameraPivotTests.cc.
References empty_strct.
Referenced by cempty().
initial()
GU::CameraPivot CGTEST::CameraPivotCPPTests::initial () inline protected virtual
Implements CGTEST::GUCoordinatesTests< Class >.
Definition at line 89 of file CameraPivotTests.cc.
References cameras.
preamble()
void CGTEST::CameraPivotCPPTests::preamble () inline protected virtual
Reimplemented from CGTEST::GUCoordinatesTests< Class >.
Definition at line 70 of file CameraPivotTests.cc.
References gu_camera_pivot::cameras, cameras, gu_camera::centerOffset, empty_strct, GU_CAMERA_PIVOT_NUM_CAMERAS, GU_NAO_V5_BOTTOM_CAMERA, GU_NAO_V5_TOP_CAMERA, gu_camera::height, gu_camera_pivot::height, gu_camera::hFov, gu_camera_pivot::numCameras, gu_camera_pivot::pitch, gu_camera::vDirection, gu_camera::vFov, and gu_camera_pivot::yaw.
Member Data Documentation
cameras
gu_camera CGTEST::CameraPivotCPPTests::cameras[2] protected
Definition at line 67 of file CameraPivotTests.cc.
Referenced by cchange(), initial(), and preamble().
empty_strct
gu_camera_pivot CGTEST::CameraPivotCPPTests::empty_strct protected
Definition at line 68 of file CameraPivotTests.cc.
Referenced by empty(), and preamble().
The documentation for this class was generated from the following file:
tests/CameraPivotTests.cc