gucoordinates: CGTEST::GUCoordinatesTests< Class > Class Template Reference
CGTEST::GUCoordinatesTests< Class > Class Template Reference abstract
#include <gucoordinates_tests.hpp>
Protected Member Functions
virtual void SetUp ()
virtual void TearDown ()
void camera_equal (const gu_camera_coordinate lhs, const gu_camera_coordinate rhs)
void pixel_equal (const gu_pixel_coordinate lhs, const gu_pixel_coordinate rhs)
void percent_equal (const gu_percent_coordinate lhs, const gu_percent_coordinate rhs)
void percent_near (const gu_percent_coordinate lhs, const gu_percent_coordinate rhs)
virtual void SetUp ()
virtual void TearDown ()
virtual void preamble ()
virtual Class initial ()=0
virtual void change (Class &)
virtual Class empty ()=0
void ro3_test ()
void ro5_test ()
bool near (const double lhs, const double rhs) const
void assert_near (const double lhs, const double rhs, const double tolerance) const
void equals (const GU::CameraCoordinate lhs, const GU::CameraCoordinate rhs)
void nequals (const GU::CameraCoordinate lhs, const GU::CameraCoordinate rhs)
void equals (const GU::Camera lhs, const GU::Camera rhs)
void nequals (const GU::Camera lhs, const GU::Camera rhs)
void equals (const GU::PixelCoordinate lhs, const GU::PixelCoordinate rhs)
void nequals (const GU::PixelCoordinate lhs, const GU::PixelCoordinate rhs)
void equals (const GU::PercentCoordinate lhs, const GU::PercentCoordinate rhs)
void nequals (const GU::PercentCoordinate lhs, const GU::PercentCoordinate rhs)
void equals (const GU::RelativeCoordinate lhs, const GU::RelativeCoordinate rhs)
void nequals (const GU::RelativeCoordinate lhs, const GU::RelativeCoordinate rhs)
void equals (const GU::CartesianCoordinate lhs, const GU::CartesianCoordinate rhs)
void nequals (const GU::CartesianCoordinate lhs, const GU::CartesianCoordinate rhs)
void equals (const GU::FieldCoordinate lhs, const GU::FieldCoordinate rhs)
void nequals (const GU::FieldCoordinate lhs, const GU::FieldCoordinate rhs)
void equals (const GU::CameraPivot lhs, const GU::CameraPivot rhs)
void nequals (const GU::CameraPivot lhs, const GU::CameraPivot rhs)
void equals (const GU::OptionalCameraCoordinate lhs, const GU::OptionalCameraCoordinate rhs)
void nequals (const GU::OptionalCameraCoordinate lhs, const GU::OptionalCameraCoordinate rhs)
void equals (const GU::OptionalPixelCoordinate lhs, const GU::OptionalPixelCoordinate rhs)
void nequals (const GU::OptionalPixelCoordinate lhs, const GU::OptionalPixelCoordinate rhs)
void equals (const GU::OptionalPercentCoordinate lhs, const GU::OptionalPercentCoordinate rhs)
void nequals (const GU::OptionalPercentCoordinate lhs, const GU::OptionalPercentCoordinate rhs)
void equals (const GU::OptionalRelativeCoordinate lhs, const GU::OptionalRelativeCoordinate rhs)
void nequals (const GU::OptionalRelativeCoordinate lhs, const GU::OptionalRelativeCoordinate rhs)
void equals (const GU::OptionalCartesianCoordinate lhs, const GU::OptionalCartesianCoordinate rhs)
void nequals (const GU::OptionalCartesianCoordinate lhs, const GU::OptionalCartesianCoordinate rhs)
void equals (const GU::OptionalFieldCoordinate lhs, const GU::OptionalFieldCoordinate rhs)
void nequals (const GU::OptionalFieldCoordinate lhs, const GU::OptionalFieldCoordinate rhs)
Protected Attributes
GU::CameraPivot nao
GU::Camera topCamera
GU::Camera bottomCamera
Detailed Description
template<typename Class>
class CGTEST::GUCoordinatesTests< Class >
Definition at line 100 of file gucoordinates_tests.hpp.
Member Function Documentation
assert_near()
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::assert_near (const double lhs, const double rhs, const double tolerance) const inline protected
Definition at line 230 of file GUCoordinatesTests.hpp.
camera_equal()
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::camera_equal (const gu_camera_coordinate lhs, const gu_camera_coordinate rhs) inline protected
Definition at line 107 of file gucoordinates_tests.hpp.
References gu_camera_coordinate::res_height, gu_camera_coordinate::res_width, gu_camera_coordinate::x, and gu_camera_coordinate::y.
change()
template<typename Class > virtual void CGTEST::GUCoordinatesTests< Class >::change (Class &) inline protected virtual
Definition at line 166 of file GUCoordinatesTests.hpp.
Referenced by CGTEST::GUCoordinatesTests< Class >::ro3_test().
empty()
template<typename Class > virtual Class CGTEST::GUCoordinatesTests< Class >::empty () protected pure virtual
Implemented in CGTEST::CameraCoordinateCPPTests, CGTEST::CameraPivotCPPTests, CGTEST::CameraCPPTests, CGTEST::CartesianCoordinateCPPTests, CGTEST::FieldCoordinateCPPTests, CGTEST::PercentCoordinateCPPTests, CGTEST::PixelCoordinateCPPTests, and CGTEST::RelativeCoordinateCPPTests.
Referenced by CGTEST::GUCoordinatesTests< Class >::ro5_test().
equals() [1/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::equals (const GU::Camera lhs, const GU::Camera rhs) inline protected
Definition at line 252 of file GUCoordinatesTests.hpp.
References GU::Camera::centerOffset(), GU::Camera::height(), GU::Camera::hFov(), CGTEST::GUCoordinatesTests< Class >::near(), GU::Camera::vDirection(), and GU::Camera::vFov().
equals() [2/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::equals (const GU::CameraCoordinate lhs, const GU::CameraCoordinate rhs) inline protected
Definition at line 235 of file GUCoordinatesTests.hpp.
References GU::CameraCoordinate::resHeight(), GU::CameraCoordinate::resWidth(), GU::CameraCoordinate::x(), and GU::CameraCoordinate::y().
Referenced by CGTEST::GUWrapperTests< Class, Strct >::c_convertible_test(), CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::ro3_test(), and CGTEST::GUCoordinatesTests< Class >::ro5_test().
equals() [3/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::equals (const GU::CameraPivot lhs, const GU::CameraPivot rhs) inline protected
Definition at line 344 of file GUCoordinatesTests.hpp.
References GU::CameraPivot::camera(), GU::Camera::centerOffset(), GU::Camera::height(), GU::CameraPivot::height(), GU::Camera::hFov(), CGTEST::GUCoordinatesTests< Class >::near(), GU::CameraPivot::numCameras(), GU::CameraPivot::pitch(), GU::Camera::vDirection(), GU::Camera::vFov(), and GU::CameraPivot::yaw().
equals() [4/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::equals (const GU::CartesianCoordinate lhs, const GU::CartesianCoordinate rhs) inline protected
Definition at line 318 of file GUCoordinatesTests.hpp.
References GU::CartesianCoordinate::x(), and GU::CartesianCoordinate::y().
equals() [5/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::equals (const GU::FieldCoordinate lhs, const GU::FieldCoordinate rhs) inline protected
Definition at line 329 of file GUCoordinatesTests.hpp.
References CGTEST::GUCoordinatesTests< Class >::equals(), GU::FieldCoordinate::heading(), and GU::FieldCoordinate::position().
equals() [6/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::equals (const GU::OptionalCameraCoordinate lhs, const GU::OptionalCameraCoordinate rhs) inline protected
Definition at line 391 of file GUCoordinatesTests.hpp.
References CGTEST::GUCoordinatesTests< Class >::equals(), GU::OptionalCoordinate< Raw, Wrapped >::has_value(), and GU::OptionalCoordinate< Raw, Wrapped >::value().
equals() [7/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::equals (const GU::OptionalCartesianCoordinate lhs, const GU::OptionalCartesianCoordinate rhs) inline protected
Definition at line 455 of file GUCoordinatesTests.hpp.
References CGTEST::GUCoordinatesTests< Class >::equals(), GU::OptionalCoordinate< Raw, Wrapped >::has_value(), and GU::OptionalCoordinate< Raw, Wrapped >::value().
equals() [8/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::equals (const GU::OptionalFieldCoordinate lhs, const GU::OptionalFieldCoordinate rhs) inline protected
Definition at line 471 of file GUCoordinatesTests.hpp.
References CGTEST::GUCoordinatesTests< Class >::equals(), GU::OptionalCoordinate< Raw, Wrapped >::has_value(), and GU::OptionalCoordinate< Raw, Wrapped >::value().
equals() [9/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::equals (const GU::OptionalPercentCoordinate lhs, const GU::OptionalPercentCoordinate rhs) inline protected
Definition at line 423 of file GUCoordinatesTests.hpp.
References CGTEST::GUCoordinatesTests< Class >::equals(), GU::OptionalCoordinate< Raw, Wrapped >::has_value(), and GU::OptionalCoordinate< Raw, Wrapped >::value().
equals() [10/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::equals (const GU::OptionalPixelCoordinate lhs, const GU::OptionalPixelCoordinate rhs) inline protected
Definition at line 407 of file GUCoordinatesTests.hpp.
References CGTEST::GUCoordinatesTests< Class >::equals(), GU::OptionalCoordinate< Raw, Wrapped >::has_value(), and GU::OptionalCoordinate< Raw, Wrapped >::value().
equals() [11/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::equals (const GU::OptionalRelativeCoordinate lhs, const GU::OptionalRelativeCoordinate rhs) inline protected
Definition at line 439 of file GUCoordinatesTests.hpp.
References CGTEST::GUCoordinatesTests< Class >::equals(), GU::OptionalCoordinate< Raw, Wrapped >::has_value(), and GU::OptionalCoordinate< Raw, Wrapped >::value().
equals() [12/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::equals (const GU::PercentCoordinate lhs, const GU::PercentCoordinate rhs) inline protected
Definition at line 290 of file GUCoordinatesTests.hpp.
References CGTEST::GUCoordinatesTests< Class >::near(), GU::PercentCoordinate::x(), and GU::PercentCoordinate::y().
equals() [13/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::equals (const GU::PixelCoordinate lhs, const GU::PixelCoordinate rhs) inline protected
Definition at line 272 of file GUCoordinatesTests.hpp.
References GU::PixelCoordinate::resHeight(), GU::PixelCoordinate::resWidth(), GU::PixelCoordinate::x(), and GU::PixelCoordinate::y().
equals() [14/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::equals (const GU::RelativeCoordinate lhs, const GU::RelativeCoordinate rhs) inline protected
Definition at line 304 of file GUCoordinatesTests.hpp.
References GU::RelativeCoordinate::direction(), and GU::RelativeCoordinate::distance().
initial()
template<typename Class > virtual Class CGTEST::GUCoordinatesTests< Class >::initial () protected pure virtual
Implemented in CGTEST::CameraCoordinateCPPTests, CGTEST::CameraPivotCPPTests, CGTEST::CameraCPPTests, CGTEST::CartesianCoordinateCPPTests, CGTEST::FieldCoordinateCPPTests, CGTEST::PercentCoordinateCPPTests, CGTEST::PixelCoordinateCPPTests, and CGTEST::RelativeCoordinateCPPTests.
Referenced by CGTEST::GUCoordinatesTests< Class >::ro3_test(), and CGTEST::GUCoordinatesTests< Class >::ro5_test().
near()
template<typename Class > bool CGTEST::GUCoordinatesTests< Class >::near (const double lhs, const double rhs) const inline protected
Definition at line 224 of file GUCoordinatesTests.hpp.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), and CGTEST::GUCoordinatesTests< Class >::nequals().
nequals() [1/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::nequals (const GU::Camera lhs, const GU::Camera rhs) inline protected
Definition at line 261 of file GUCoordinatesTests.hpp.
References GU::Camera::centerOffset(), GU::Camera::height(), GU::Camera::hFov(), CGTEST::GUCoordinatesTests< Class >::near(), GU::Camera::vDirection(), and GU::Camera::vFov().
nequals() [2/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::nequals (const GU::CameraCoordinate lhs, const GU::CameraCoordinate rhs) inline protected
Definition at line 243 of file GUCoordinatesTests.hpp.
References GU::CameraCoordinate::resHeight(), GU::CameraCoordinate::resWidth(), GU::CameraCoordinate::x(), and GU::CameraCoordinate::y().
Referenced by CGTEST::GUCoordinatesTests< Class >::nequals(), CGTEST::GUCoordinatesTests< Class >::ro3_test(), and CGTEST::GUCoordinatesTests< Class >::ro5_test().
nequals() [3/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::nequals (const GU::CameraPivot lhs, const GU::CameraPivot rhs) inline protected
Definition at line 362 of file GUCoordinatesTests.hpp.
References GU::CameraPivot::camera(), GU::Camera::centerOffset(), GU::Camera::height(), GU::CameraPivot::height(), GU::Camera::hFov(), CGTEST::GUCoordinatesTests< Class >::near(), GU::CameraPivot::numCameras(), GU::CameraPivot::pitch(), GU::Camera::vDirection(), GU::Camera::vFov(), and GU::CameraPivot::yaw().
nequals() [4/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::nequals (const GU::CartesianCoordinate lhs, const GU::CartesianCoordinate rhs) inline protected
Definition at line 324 of file GUCoordinatesTests.hpp.
References GU::CartesianCoordinate::x(), and GU::CartesianCoordinate::y().
nequals() [5/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::nequals (const GU::FieldCoordinate lhs, const GU::FieldCoordinate rhs) inline protected
Definition at line 335 of file GUCoordinatesTests.hpp.
References GU::FieldCoordinate::heading(), GU::FieldCoordinate::position(), GU::CartesianCoordinate::x(), and GU::CartesianCoordinate::y().
nequals() [6/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::nequals (const GU::OptionalCameraCoordinate lhs, const GU::OptionalCameraCoordinate rhs) inline protected
Definition at line 397 of file GUCoordinatesTests.hpp.
References GU::OptionalCoordinate< Raw, Wrapped >::has_value(), CGTEST::GUCoordinatesTests< Class >::nequals(), and GU::OptionalCoordinate< Raw, Wrapped >::value().
nequals() [7/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::nequals (const GU::OptionalCartesianCoordinate lhs, const GU::OptionalCartesianCoordinate rhs) inline protected
Definition at line 461 of file GUCoordinatesTests.hpp.
References GU::OptionalCoordinate< Raw, Wrapped >::has_value(), CGTEST::GUCoordinatesTests< Class >::nequals(), and GU::OptionalCoordinate< Raw, Wrapped >::value().
nequals() [8/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::nequals (const GU::OptionalFieldCoordinate lhs, const GU::OptionalFieldCoordinate rhs) inline protected
Definition at line 477 of file GUCoordinatesTests.hpp.
References GU::OptionalCoordinate< Raw, Wrapped >::has_value(), CGTEST::GUCoordinatesTests< Class >::nequals(), and GU::OptionalCoordinate< Raw, Wrapped >::value().
nequals() [9/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::nequals (const GU::OptionalPercentCoordinate lhs, const GU::OptionalPercentCoordinate rhs) inline protected
Definition at line 429 of file GUCoordinatesTests.hpp.
References GU::OptionalCoordinate< Raw, Wrapped >::has_value(), CGTEST::GUCoordinatesTests< Class >::nequals(), and GU::OptionalCoordinate< Raw, Wrapped >::value().
nequals() [10/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::nequals (const GU::OptionalPixelCoordinate lhs, const GU::OptionalPixelCoordinate rhs) inline protected
Definition at line 413 of file GUCoordinatesTests.hpp.
References GU::OptionalCoordinate< Raw, Wrapped >::has_value(), CGTEST::GUCoordinatesTests< Class >::nequals(), and GU::OptionalCoordinate< Raw, Wrapped >::value().
nequals() [11/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::nequals (const GU::OptionalRelativeCoordinate lhs, const GU::OptionalRelativeCoordinate rhs) inline protected
Definition at line 445 of file GUCoordinatesTests.hpp.
References GU::OptionalCoordinate< Raw, Wrapped >::has_value(), CGTEST::GUCoordinatesTests< Class >::nequals(), and GU::OptionalCoordinate< Raw, Wrapped >::value().
nequals() [12/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::nequals (const GU::PercentCoordinate lhs, const GU::PercentCoordinate rhs) inline protected
Definition at line 296 of file GUCoordinatesTests.hpp.
References CGTEST::GUCoordinatesTests< Class >::near(), GU::PercentCoordinate::x(), and GU::PercentCoordinate::y().
nequals() [13/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::nequals (const GU::PixelCoordinate lhs, const GU::PixelCoordinate rhs) inline protected
Definition at line 280 of file GUCoordinatesTests.hpp.
References GU::PixelCoordinate::resHeight(), GU::PixelCoordinate::resWidth(), GU::PixelCoordinate::x(), and GU::PixelCoordinate::y().
nequals() [14/14]
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::nequals (const GU::RelativeCoordinate lhs, const GU::RelativeCoordinate rhs) inline protected
Definition at line 310 of file GUCoordinatesTests.hpp.
References GU::RelativeCoordinate::direction(), GU::RelativeCoordinate::distance(), and CGTEST::GUCoordinatesTests< Class >::near().
percent_equal()
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::percent_equal (const gu_percent_coordinate lhs, const gu_percent_coordinate rhs) inline protected
Definition at line 123 of file gucoordinates_tests.hpp.
References gu_percent_coordinate::x, and gu_percent_coordinate::y.
percent_near()
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::percent_near (const gu_percent_coordinate lhs, const gu_percent_coordinate rhs) inline protected
Definition at line 129 of file gucoordinates_tests.hpp.
References gu_percent_coordinate::x, and gu_percent_coordinate::y.
pixel_equal()
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::pixel_equal (const gu_pixel_coordinate lhs, const gu_pixel_coordinate rhs) inline protected
Definition at line 115 of file gucoordinates_tests.hpp.
References gu_pixel_coordinate::res_height, gu_pixel_coordinate::res_width, gu_pixel_coordinate::x, and gu_pixel_coordinate::y.
preamble()
template<typename Class > virtual void CGTEST::GUCoordinatesTests< Class >::preamble () inline protected virtual
Reimplemented in CGTEST::CameraPivotCPPTests.
Definition at line 162 of file GUCoordinatesTests.hpp.
Referenced by CGTEST::GUCoordinatesTests< Class >::ro3_test().
ro3_test()
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::ro3_test () inline protected
Definition at line 170 of file GUCoordinatesTests.hpp.
References CGTEST::GUCoordinatesTests< Class >::change(), CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::initial(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::GUCoordinatesTests< Class >::preamble().
ro5_test()
template<typename Class > void CGTEST::GUCoordinatesTests< Class >::ro5_test () inline protected
Definition at line 197 of file GUCoordinatesTests.hpp.
References CGTEST::GUCoordinatesTests< Class >::empty(), CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::initial(), and CGTEST::GUCoordinatesTests< Class >::nequals().
SetUp() [1/2]
template<typename Class > virtual void CGTEST::GUCoordinatesTests< Class >::SetUp () inline protected virtual
Definition at line 103 of file gucoordinates_tests.hpp.
SetUp() [2/2]
template<typename Class > virtual void CGTEST::GUCoordinatesTests< Class >::SetUp () inline protected virtual
Definition at line 149 of file GUCoordinatesTests.hpp.
References ALL_FAKES, CGTEST::GUCoordinatesTests< Class >::bottomCamera, FFF_RESET_HISTORY, GU_NAO_V5_BOTTOM_CAMERA, GU_NAO_V5_HEAD, GU_NAO_V5_TOP_CAMERA, CGTEST::GUCoordinatesTests< Class >::nao, RESET_FAKE, and CGTEST::GUCoordinatesTests< Class >::topCamera.
TearDown() [1/2]
template<typename Class > virtual void CGTEST::GUCoordinatesTests< Class >::TearDown () inline protected virtual
Definition at line 105 of file gucoordinates_tests.hpp.
TearDown() [2/2]
template<typename Class > virtual void CGTEST::GUCoordinatesTests< Class >::TearDown () inline protected virtual
Definition at line 157 of file GUCoordinatesTests.hpp.
References ALL_FAKES, FFF_RESET_HISTORY, and RESET_FAKE.
Member Data Documentation
bottomCamera
template<typename Class > GU::Camera CGTEST::GUCoordinatesTests< Class >::bottomCamera protected
Definition at line 147 of file GUCoordinatesTests.hpp.
Referenced by CGTEST::GUCoordinatesTests< Class >::SetUp().
nao
template<typename Class > GU::CameraPivot CGTEST::GUCoordinatesTests< Class >::nao protected
Definition at line 145 of file GUCoordinatesTests.hpp.
Referenced by CGTEST::GUCoordinatesTests< Class >::SetUp().
topCamera
template<typename Class > GU::Camera CGTEST::GUCoordinatesTests< Class >::topCamera protected
Definition at line 146 of file GUCoordinatesTests.hpp.
Referenced by CGTEST::GUCoordinatesTests< Class >::SetUp().
The documentation for this class was generated from the following files:
ctests/gucoordinates_tests.hpp
tests/GUCoordinatesTests.hpp