gucoordinates: conversions.c File Reference
conversions.c File Reference
#include "conversions.h"
#include "hidden_conversions.h"
#include <math.h>
#include <float.h>
#include <stdio.h>
Macros
#define M_PI_2 1.57079632679489661923
#define RELATIVE_COORD_MAX_DISTANCE f_to_mm_u(FLT_MAX)
Functions
gu_pixel_coordinate cam_coord_to_px_coord (const gu_camera_coordinate coord)
gu_camera_coordinate px_coord_to_cam_coord (const gu_pixel_coordinate coord)
gu_percent_coordinate px_coord_to_pct_coord (const gu_pixel_coordinate coord)
gu_pixel_coordinate pct_coord_to_px_coord (const gu_percent_coordinate coord, const pixels_u res_width, const pixels_u res_height)
gu_relative_coordinate pct_coord_to_rr_coord (const gu_percent_coordinate coord, const gu_camera_pivot camera_pivot, const int cameraOffset)
gu_percent_coordinate rr_coord_to_pct_coord (const gu_relative_coordinate coord, const gu_camera_pivot camera_pivot, const int cameraOffset)
gu_percent_coordinate clamped_rr_coord_to_pct_coord (const gu_relative_coordinate coord, const gu_camera_pivot camera_pivot, const int cameraOffset)
gu_cartesian_coordinate rr_coord_to_cartesian_coord (const gu_relative_coordinate coord)
gu_cartesian_coordinate rr_coord_to_cartesian_coord_from_source (const gu_relative_coordinate coord, const gu_cartesian_coordinate source)
gu_cartesian_coordinate rr_coord_to_cartesian_coord_from_field (const gu_relative_coordinate coord, const gu_field_coordinate source)
gu_field_coordinate rr_coord_to_field_coord (const gu_relative_coordinate coord, const degrees_t heading)
gu_field_coordinate rr_coord_to_field_coord_from_source (const gu_relative_coordinate coord, const gu_field_coordinate source, const degrees_t heading)
gu_relative_coordinate cartesian_coord_to_rr_coord (const gu_cartesian_coordinate target)
gu_relative_coordinate cartesian_coord_to_rr_coord_from_source (const gu_cartesian_coordinate source, const gu_cartesian_coordinate target)
gu_relative_coordinate field_coord_to_rr_coord_to_target (const gu_field_coordinate source, const gu_cartesian_coordinate target)
radians_d angle_between_points (const gu_cartesian_coordinate p1, const gu_cartesian_coordinate p2)
millimetres_d distance_between_points (const gu_cartesian_coordinate point1, const gu_cartesian_coordinate point2)
degrees_d normalise_deg_d (degrees_d angle)
degrees_t normalise_deg_t (degrees_t angle)
radians_d normalise_rad_d (radians_d angle)
Macro Definition Documentation
M_PI_2
#define M_PI_2 1.57079632679489661923
Definition at line 70 of file conversions.c.
RELATIVE_COORD_MAX_DISTANCE
#define RELATIVE_COORD_MAX_DISTANCE f_to_mm_u(FLT_MAX)
Definition at line 73 of file conversions.c.
Function Documentation
angle_between_points()
radians_d angle_between_points (const gu_cartesian_coordinate p1, const gu_cartesian_coordinate p2)
Definition at line 244 of file conversions.c.
References gu_cartesian_coordinate::x, and gu_cartesian_coordinate::y.
Referenced by cartesian_coord_to_rr_coord_from_source().
cam_coord_to_px_coord()
gu_pixel_coordinate cam_coord_to_px_coord (const gu_camera_coordinate coord)
Definition at line 75 of file conversions.c.
References gu_camera_coordinate::res_height, gu_camera_coordinate::res_width, gu_camera_coordinate::x, and gu_camera_coordinate::y.
Referenced by GU::CameraCoordinate::pixelCoordinate(), and CGTEST::TEST_F().
cartesian_coord_to_rr_coord()
gu_relative_coordinate cartesian_coord_to_rr_coord (const gu_cartesian_coordinate target)
Definition at line 220 of file conversions.c.
References cartesian_coord_to_rr_coord_from_source().
cartesian_coord_to_rr_coord_from_source()
gu_relative_coordinate cartesian_coord_to_rr_coord_from_source (const gu_cartesian_coordinate source, const gu_cartesian_coordinate target)
Definition at line 226 of file conversions.c.
References angle_between_points(), and distance_between_points().
Referenced by cartesian_coord_to_rr_coord(), field_coord_to_rr_coord_to_target(), GU::CartesianCoordinate::relativeCoordinateTo(), and CGTEST::TEST_F().
clamped_rr_coord_to_pct_coord()
gu_percent_coordinate clamped_rr_coord_to_pct_coord (const gu_relative_coordinate coord, const gu_camera_pivot camera_pivot, const int cameraOffset)
Definition at line 157 of file conversions.c.
References rr_coord_to_pct_coord(), gu_percent_coordinate::x, and gu_percent_coordinate::y.
Referenced by GU::RelativeCoordinate::clampedPercentCoordinate(), and CGTEST::TEST_F().
distance_between_points()
millimetres_d distance_between_points (const gu_cartesian_coordinate point1, const gu_cartesian_coordinate point2)
Definition at line 257 of file conversions.c.
References gu_cartesian_coordinate::x, and gu_cartesian_coordinate::y.
Referenced by cartesian_coord_to_rr_coord_from_source().
field_coord_to_rr_coord_to_target()
gu_relative_coordinate field_coord_to_rr_coord_to_target (const gu_field_coordinate source, const gu_cartesian_coordinate target)
Definition at line 237 of file conversions.c.
References cartesian_coord_to_rr_coord_from_source(), gu_relative_coordinate::direction, gu_field_coordinate::heading, normalise_deg_d(), and gu_field_coordinate::position.
Referenced by GU::FieldCoordinate::relativeCoordinateTo(), and CGTEST::TEST_F().
normalise_deg_d()
degrees_d normalise_deg_d (degrees_d angle)
Definition at line 271 of file conversions.c.
Referenced by field_coord_to_rr_coord_to_target(), normalise_deg_t(), and normalise_rad_d().
normalise_deg_t()
degrees_t normalise_deg_t (degrees_t angle)
Definition at line 290 of file conversions.c.
References normalise_deg_d().
normalise_rad_d()
radians_d normalise_rad_d (radians_d angle)
Definition at line 294 of file conversions.c.
References normalise_deg_d().
pct_coord_to_px_coord()
gu_pixel_coordinate pct_coord_to_px_coord (const gu_percent_coordinate coord, const pixels_u res_width, const pixels_u res_height)
Definition at line 105 of file conversions.c.
References gu_percent_coordinate::x, and gu_percent_coordinate::y.
Referenced by GU::PercentCoordinate::pixelCoordinate(), and CGTEST::TEST_F().
pct_coord_to_rr_coord()
gu_relative_coordinate pct_coord_to_rr_coord (const gu_percent_coordinate coord, const gu_camera_pivot camera_pivot, const int cameraOffset)
Definition at line 115 of file conversions.c.
References gu_camera_pivot::cameras, gu_camera::centerOffset, gu_camera_pivot_calculate_camera_height(), gu_camera::hFov, M_PI_2, gu_camera_pivot::pitch, RELATIVE_COORD_MAX_DISTANCE, gu_camera::vDirection, gu_camera::vFov, gu_percent_coordinate::x, gu_percent_coordinate::y, and gu_camera_pivot::yaw.
Referenced by GU::PercentCoordinate::relativeCoordinate(), and CGTEST::TEST_F().
px_coord_to_cam_coord()
gu_camera_coordinate px_coord_to_cam_coord (const gu_pixel_coordinate coord)
Definition at line 85 of file conversions.c.
References gu_pixel_coordinate::res_height, gu_pixel_coordinate::res_width, gu_pixel_coordinate::x, and gu_pixel_coordinate::y.
Referenced by GU::PixelCoordinate::cameraCoordinate(), and CGTEST::TEST_F().
px_coord_to_pct_coord()
gu_percent_coordinate px_coord_to_pct_coord (const gu_pixel_coordinate coord)
Definition at line 95 of file conversions.c.
References gu_pixel_coordinate::res_height, gu_pixel_coordinate::res_width, gu_pixel_coordinate::x, and gu_pixel_coordinate::y.
Referenced by GU::PixelCoordinate::percentCoordinate(), and CGTEST::TEST_F().
rr_coord_to_cartesian_coord()
gu_cartesian_coordinate rr_coord_to_cartesian_coord (const gu_relative_coordinate coord)
Definition at line 177 of file conversions.c.
References gu_relative_coordinate::direction, and gu_relative_coordinate::distance.
Referenced by GU::RelativeCoordinate::cartesianCoordinate(), rr_coord_to_cartesian_coord_from_source(), and rr_coord_to_field_coord().
rr_coord_to_cartesian_coord_from_field()
gu_cartesian_coordinate rr_coord_to_cartesian_coord_from_field (const gu_relative_coordinate coord, const gu_field_coordinate source)
Definition at line 196 of file conversions.c.
References gu_relative_coordinate::direction, gu_relative_coordinate::distance, gu_field_coordinate::heading, gu_field_coordinate::position, and rr_coord_to_cartesian_coord_from_source().
Referenced by GU::FieldCoordinate::cartesianCoordinateAt(), and CGTEST::TEST_F().
rr_coord_to_cartesian_coord_from_source()
gu_cartesian_coordinate rr_coord_to_cartesian_coord_from_source (const gu_relative_coordinate coord, const gu_cartesian_coordinate source)
Definition at line 188 of file conversions.c.
References rr_coord_to_cartesian_coord(), gu_cartesian_coordinate::x, and gu_cartesian_coordinate::y.
Referenced by GU::CartesianCoordinate::cartesianCoordinateAt(), rr_coord_to_cartesian_coord_from_field(), rr_coord_to_field_coord_from_source(), and CGTEST::TEST_F().
rr_coord_to_field_coord()
gu_field_coordinate rr_coord_to_field_coord (const gu_relative_coordinate coord, const degrees_t heading)
Definition at line 202 of file conversions.c.
References gu_field_coordinate::heading, gu_field_coordinate::position, and rr_coord_to_cartesian_coord().
Referenced by GU::RelativeCoordinate::fieldCoordinate(), and CGTEST::TEST_F().
rr_coord_to_field_coord_from_source()
gu_field_coordinate rr_coord_to_field_coord_from_source (const gu_relative_coordinate coord, const gu_field_coordinate source, const degrees_t heading)
Definition at line 211 of file conversions.c.
References gu_relative_coordinate::direction, gu_field_coordinate::heading, gu_field_coordinate::position, and rr_coord_to_cartesian_coord_from_source().
Referenced by GU::FieldCoordinate::fieldCoordinateAt(), and CGTEST::TEST_F().
rr_coord_to_pct_coord()
gu_percent_coordinate rr_coord_to_pct_coord (const gu_relative_coordinate coord, const gu_camera_pivot camera_pivot, const int cameraOffset)
Definition at line 142 of file conversions.c.
References gu_camera_pivot::cameras, gu_camera::centerOffset, gu_relative_coordinate::direction, gu_relative_coordinate::distance, gu_camera_pivot_calculate_camera_height(), gu_camera::hFov, gu_camera_pivot::pitch, gu_camera::vDirection, gu_camera::vFov, and gu_camera_pivot::yaw.
Referenced by clamped_rr_coord_to_pct_coord(), GU::RelativeCoordinate::percentCoordinate(), and CGTEST::TEST_F().