gucoordinates: CGTEST Namespace Reference
CGTEST Namespace Reference
Classes
class CameraCoordinateCPPTests
class CameraCoordinateTests
class CameraCPPTests
class CameraPivotCPPTests
class CameraTests
class CartesianCoordinateCPPTests
class CartesianCoordinateTests
class ConversionsTests
class FieldCoordinateCPPTests
class FieldCoordinateTests
class GUCoordinatesTests
class GUWrapperTests
class PercentCoordinateCPPTests
class PercentCoordinateTests
class PixelCoordinateCPPTests
class PixelCoordinateTests
class RelativeCoordinateCPPTests
class RelativeCoordinateTests
class RobotTests
Functions
TEST_F (CameraCoordinateTests, Equality)
TEST_F (RobotTests, Equality)
TEST_F (CameraTests, Equality)
TEST_F (CartesianCoordinateTests, Equality)
TEST_F (ConversionsTests, ConvertsToCorrectPercentCoordinate)
TEST_F (ConversionsTests, ConvertsToCorrectPixelCoordinate)
TEST_F (ConversionsTests, ConvertsFromCameraToPixelCoordinate)
TEST_F (ConversionsTests, ConvertsFromPixelToCameraCoordinate)
TEST_F (ConversionsTests, ConvertsFromPercentToRelativeCoordinate)
TEST_F (ConversionsTests, ConvertsFromPercentToRelativeCoordinate3)
TEST_F (ConversionsTests, ConvertsFromRelativeCoordinateToPercent)
TEST_F (ConversionsTests, ConvertsFromRelativeCoordinateToPercent2)
TEST_F (ConversionsTests, ConvertsFromRelativeCoordinateToPercent3)
TEST_F (ConversionsTests, ConvertsFromRelativeCoordinateToPercentClamped)
TEST_F (ConversionsTests, ConvertsFromRelativeCoordinateToFieldCoordinate)
TEST_F (ConversionsTests, ConvertsToRelativeCoordinateFromFieldSource)
TEST_F (ConversionsTests, ConvertsFromFieldCoordinateToRelativeCoordinate)
TEST_F (ConversionsTests, ConvertsFromRelativeToCartesianFromSource)
TEST_F (ConversionsTests, ConvertesFromCartesianToRelativeFromSource)
TEST_F (ConversionsTests, ConvertsToFieldFromRelativeFromField)
TEST_F (ConversionsTests, ConvertsToRelativeFromFieldToTarget)
TEST_F (FieldCoordinateTests, Equality)
TEST_F (PercentCoordinateTests, Equality)
TEST_F (PixelCoordinateTests, Equality)
TEST_F (RelativeCoordinateTests, Equality)
TEST_F (CameraCoordinateCPPTests, RO3)
TEST_F (CameraCoordinateCPPTests, RO5)
TEST_F (CameraCoordinateCPPTests, ConvertibleToC)
TEST_F (CameraCoordinateCPPTests, Equality)
TEST_F (CameraCoordinateCPPTests, TO_C)
TEST_F (CameraCoordinateCPPTests, PixelCoordinate)
TEST_F (CameraCoordinateCPPTests, PercentCoordinate)
TEST_F (CameraCoordinateCPPTests, relativeCoordinate)
TEST_F (CameraCoordinateCPPTests, GettersSetters)
TEST_F (CameraPivotCPPTests, RO3)
TEST_F (CameraPivotCPPTests, RO5)
TEST_F (CameraPivotCPPTests, ConvertibleToC)
TEST_F (CameraPivotCPPTests, Equality)
TEST_F (CameraPivotCPPTests, TO_C)
TEST_F (CameraPivotCPPTests, GettersSetters)
TEST_F (CameraCPPTests, RO3)
TEST_F (CameraCPPTests, RO5)
TEST_F (CameraCPPTests, ConvertibleToC)
TEST_F (CameraCPPTests, Equality)
TEST_F (CameraCPPTests, TO_C)
TEST_F (CameraCPPTests, GettersSetters)
TEST_F (CartesianCoordinateCPPTests, RO3)
TEST_F (CartesianCoordinateCPPTests, RO5)
TEST_F (CartesianCoordinateCPPTests, ConvertibleToC)
TEST_F (CartesianCoordinateCPPTests, Equality)
TEST_F (CartesianCoordinateCPPTests, TO_C)
TEST_F (CartesianCoordinateCPPTests, cartesianCoordinateCamera)
TEST_F (CartesianCoordinateCPPTests, cartesianCoordinatePixel)
TEST_F (CartesianCoordinateCPPTests, cartesianCoordinatePercent)
TEST_F (CartesianCoordinateCPPTests, CartesianCoordinate)
TEST_F (CartesianCoordinateCPPTests, RelativeCoordinateCartesian)
TEST_F (CartesianCoordinateCPPTests, RelativeCoordinateField)
TEST_F (CartesianCoordinateCPPTests, percentCoordinateCartesian)
TEST_F (CartesianCoordinateCPPTests, percentCoordinateField)
TEST_F (CartesianCoordinateCPPTests, pixelCoordinateCartesian)
TEST_F (CartesianCoordinateCPPTests, pixelCoordinateField)
TEST_F (CartesianCoordinateCPPTests, cameraCoordinateCartesian)
TEST_F (CartesianCoordinateCPPTests, cameraCoordinateField)
TEST_F (CartesianCoordinateCPPTests, clampedPercentCoordinateCartesian)
TEST_F (CartesianCoordinateCPPTests, clampedPercentCoordinateField)
TEST_F (CartesianCoordinateCPPTests, clampedPixelCoordinateCartesian)
TEST_F (CartesianCoordinateCPPTests, clampedPixelCoordinateField)
TEST_F (CartesianCoordinateCPPTests, clampedCameraCoordinateCartesian)
TEST_F (CartesianCoordinateCPPTests, clampedCameraCoordinateField)
TEST_F (CartesianCoordinateCPPTests, GettersSetters)
TEST_F (FieldCoordinateCPPTests, RO3)
TEST_F (FieldCoordinateCPPTests, RO5)
TEST_F (FieldCoordinateCPPTests, ConvertibleToC)
TEST_F (FieldCoordinateCPPTests, Equality)
TEST_F (FieldCoordinateCPPTests, TO_C)
TEST_F (FieldCoordinateCPPTests, cartesianCoordinateCamera)
TEST_F (FieldCoordinateCPPTests, cartesianCoordinatePixel)
TEST_F (FieldCoordinateCPPTests, cartesianCoordinatePercent)
TEST_F (FieldCoordinateCPPTests, fieldCoordinateCamera)
TEST_F (FieldCoordinateCPPTests, fieldCoordinatePixel)
TEST_F (FieldCoordinateCPPTests, fieldCoordinatePercent)
TEST_F (FieldCoordinateCPPTests, CartesianCoordinate)
TEST_F (FieldCoordinateCPPTests, FieldCoordinate)
TEST_F (FieldCoordinateCPPTests, RelativeCoordinateToCartesian)
TEST_F (FieldCoordinateCPPTests, RelativeCoordinateToField)
TEST_F (FieldCoordinateCPPTests, percentCoordinateCartesian)
TEST_F (FieldCoordinateCPPTests, percentCoordinateField)
TEST_F (FieldCoordinateCPPTests, pixelCoordinateCartesian)
TEST_F (FieldCoordinateCPPTests, pixelCoordinateField)
TEST_F (FieldCoordinateCPPTests, cameraCoordinateCartesian)
TEST_F (FieldCoordinateCPPTests, cameraCoordinateField)
TEST_F (FieldCoordinateCPPTests, clampedPercentCoordinateCartesian)
TEST_F (FieldCoordinateCPPTests, clampedPercentCoordinateField)
TEST_F (FieldCoordinateCPPTests, clampedPixelCoordinateCartesian)
TEST_F (FieldCoordinateCPPTests, clampedPixelCoordinateField)
TEST_F (FieldCoordinateCPPTests, clampedCameraCoordinateCartesian)
TEST_F (FieldCoordinateCPPTests, clampedCameraCoordinateField)
TEST_F (FieldCoordinateCPPTests, GettersSetters)
TEST_F (PercentCoordinateCPPTests, RO3)
TEST_F (PercentCoordinateCPPTests, RO5)
TEST_F (PercentCoordinateCPPTests, ConvertibleToC)
TEST_F (PercentCoordinateCPPTests, Equality)
TEST_F (PercentCoordinateCPPTests, TO_C)
TEST_F (PercentCoordinateCPPTests, CameraCoordinate)
TEST_F (PercentCoordinateCPPTests, PixelCoordinate)
TEST_F (PercentCoordinateCPPTests, relativeCoordinate)
TEST_F (PercentCoordinateCPPTests, GettersSetters)
TEST_F (PixelCoordinateCPPTests, RO3)
TEST_F (PixelCoordinateCPPTests, RO5)
TEST_F (PixelCoordinateCPPTests, ConvertibleToC)
TEST_F (PixelCoordinateCPPTests, Equality)
TEST_F (PixelCoordinateCPPTests, TO_C)
TEST_F (PixelCoordinateCPPTests, CameraCoordinate)
TEST_F (PixelCoordinateCPPTests, PercentCoordinate)
TEST_F (PixelCoordinateCPPTests, relativeCoordinate)
TEST_F (PixelCoordinateCPPTests, GettersSetters)
TEST_F (RelativeCoordinateCPPTests, RO3)
TEST_F (RelativeCoordinateCPPTests, RO5)
TEST_F (RelativeCoordinateCPPTests, ConvertibleToC)
TEST_F (RelativeCoordinateCPPTests, Equality)
TEST_F (RelativeCoordinateCPPTests, TO_C)
TEST_F (RelativeCoordinateCPPTests, CartesianCoordinate)
TEST_F (RelativeCoordinateCPPTests, FieldCoordinate)
TEST_F (RelativeCoordinateCPPTests, RelativeCoordinate)
TEST_F (RelativeCoordinateCPPTests, cameraCoordinate)
TEST_F (RelativeCoordinateCPPTests, pixelCoordinate)
TEST_F (RelativeCoordinateCPPTests, percentCoordinate)
TEST_F (RelativeCoordinateCPPTests, clampedCameraCoordinate)
TEST_F (RelativeCoordinateCPPTests, clampedPixelCoordinate)
TEST_F (RelativeCoordinateCPPTests, clampedPercentCoordinate)
TEST_F (RelativeCoordinateCPPTests, GettersSetters)
Function Documentation
TEST_F() [1/131]
CGTEST::TEST_F (CameraCoordinateCPPTests , ConvertibleToC)
Definition at line 97 of file CameraCoordinateTests.cc.
TEST_F() [2/131]
CGTEST::TEST_F (CameraCoordinateCPPTests , Equality)
Definition at line 97 of file CameraCoordinateTests.cc.
TEST_F() [3/131]
CGTEST::TEST_F (CameraCoordinateCPPTests , GettersSetters)
Definition at line 102 of file CameraCoordinateTests.cc.
References GU::CameraCoordinate::resHeight(), GU::CameraCoordinate::resWidth(), GU::CameraCoordinate::set_resHeight(), GU::CameraCoordinate::set_resWidth(), GU::CameraCoordinate::set_x(), GU::CameraCoordinate::set_y(), GU::CameraCoordinate::x(), and GU::CameraCoordinate::y().
TEST_F() [4/131]
CGTEST::TEST_F (CameraCoordinateCPPTests , PercentCoordinate)
Definition at line 99 of file CameraCoordinateTests.cc.
TEST_F() [5/131]
CGTEST::TEST_F (CameraCoordinateCPPTests , PixelCoordinate)
Definition at line 98 of file CameraCoordinateTests.cc.
TEST_F() [6/131]
CGTEST::TEST_F (CameraCoordinateCPPTests , relativeCoordinate)
Definition at line 100 of file CameraCoordinateTests.cc.
TEST_F() [7/131]
CGTEST::TEST_F (CameraCoordinateCPPTests , RO3)
Definition at line 97 of file CameraCoordinateTests.cc.
TEST_F() [8/131]
CGTEST::TEST_F (CameraCoordinateCPPTests , RO5)
Definition at line 97 of file CameraCoordinateTests.cc.
TEST_F() [9/131]
CGTEST::TEST_F (CameraCoordinateCPPTests , TO_C)
Definition at line 97 of file CameraCoordinateTests.cc.
TEST_F() [10/131]
CGTEST::TEST_F (CameraCoordinateTests , Equality)
Definition at line 65 of file camera_coordinate_tests.cc.
References gu_camera_coordinate_equals().
TEST_F() [11/131]
CGTEST::TEST_F (CameraCPPTests , ConvertibleToC)
Definition at line 98 of file CameraTests.cc.
TEST_F() [12/131]
CGTEST::TEST_F (CameraCPPTests , Equality)
Definition at line 98 of file CameraTests.cc.
TEST_F() [13/131]
CGTEST::TEST_F (CameraCPPTests , GettersSetters)
Definition at line 100 of file CameraTests.cc.
References GU::Camera::centerOffset(), GU::Camera::height(), GU::Camera::hFov(), GU::Camera::set_centerOffset(), GU::Camera::set_height(), GU::Camera::set_hFov(), GU::Camera::set_vDirection(), GU::Camera::set_vFov(), GU::Camera::vDirection(), and GU::Camera::vFov().
TEST_F() [14/131]
CGTEST::TEST_F (CameraCPPTests , RO3)
Definition at line 98 of file CameraTests.cc.
TEST_F() [15/131]
CGTEST::TEST_F (CameraCPPTests , RO5)
Definition at line 98 of file CameraTests.cc.
TEST_F() [16/131]
CGTEST::TEST_F (CameraCPPTests , TO_C)
Definition at line 98 of file CameraTests.cc.
TEST_F() [17/131]
CGTEST::TEST_F (CameraPivotCPPTests , ConvertibleToC)
Definition at line 120 of file CameraPivotTests.cc.
TEST_F() [18/131]
CGTEST::TEST_F (CameraPivotCPPTests , Equality)
Definition at line 120 of file CameraPivotTests.cc.
TEST_F() [19/131]
CGTEST::TEST_F (CameraPivotCPPTests , GettersSetters)
Definition at line 122 of file CameraPivotTests.cc.
References GU::CameraPivot::camera(), gu_camera_pivot::cameras, GU_NAO_V5_HEAD, GU::CameraPivot::height(), GU::CameraPivot::pitch(), GU::CameraPivot::set_camera(), GU::CameraPivot::set_height(), GU::CameraPivot::set_pitch(), GU::CameraPivot::set_yaw(), and GU::CameraPivot::yaw().
TEST_F() [20/131]
CGTEST::TEST_F (CameraPivotCPPTests , RO3)
Definition at line 120 of file CameraPivotTests.cc.
TEST_F() [21/131]
CGTEST::TEST_F (CameraPivotCPPTests , RO5)
Definition at line 120 of file CameraPivotTests.cc.
TEST_F() [22/131]
CGTEST::TEST_F (CameraPivotCPPTests , TO_C)
Definition at line 120 of file CameraPivotTests.cc.
TEST_F() [23/131]
CGTEST::TEST_F (CameraTests , Equality)
Definition at line 65 of file camera_tests.cc.
References gu_camera_equals(), GU_NAO_V5_BOTTOM_CAMERA, and GU_NAO_V5_TOP_CAMERA.
TEST_F() [24/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , cameraCoordinateCartesian)
Definition at line 111 of file CartesianCoordinateTests.cc.
TEST_F() [25/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , cameraCoordinateField)
Definition at line 112 of file CartesianCoordinateTests.cc.
TEST_F() [26/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , CartesianCoordinate)
Definition at line 101 of file CartesianCoordinateTests.cc.
TEST_F() [27/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , cartesianCoordinateCamera)
Definition at line 97 of file CartesianCoordinateTests.cc.
TEST_F() [28/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , cartesianCoordinatePercent)
Definition at line 99 of file CartesianCoordinateTests.cc.
TEST_F() [29/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , cartesianCoordinatePixel)
Definition at line 98 of file CartesianCoordinateTests.cc.
TEST_F() [30/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , clampedCameraCoordinateCartesian)
Definition at line 120 of file CartesianCoordinateTests.cc.
TEST_F() [31/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , clampedCameraCoordinateField)
Definition at line 121 of file CartesianCoordinateTests.cc.
TEST_F() [32/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , clampedPercentCoordinateCartesian)
Definition at line 114 of file CartesianCoordinateTests.cc.
TEST_F() [33/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , clampedPercentCoordinateField)
Definition at line 115 of file CartesianCoordinateTests.cc.
TEST_F() [34/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , clampedPixelCoordinateCartesian)
Definition at line 117 of file CartesianCoordinateTests.cc.
TEST_F() [35/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , clampedPixelCoordinateField)
Definition at line 118 of file CartesianCoordinateTests.cc.
TEST_F() [36/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , ConvertibleToC)
Definition at line 95 of file CartesianCoordinateTests.cc.
TEST_F() [37/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , Equality)
Definition at line 95 of file CartesianCoordinateTests.cc.
TEST_F() [38/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , GettersSetters)
Definition at line 124 of file CartesianCoordinateTests.cc.
References GU::CartesianCoordinate::set_x(), GU::CartesianCoordinate::set_y(), GU::CartesianCoordinate::x(), and GU::CartesianCoordinate::y().
TEST_F() [39/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , percentCoordinateCartesian)
Definition at line 105 of file CartesianCoordinateTests.cc.
TEST_F() [40/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , percentCoordinateField)
Definition at line 106 of file CartesianCoordinateTests.cc.
TEST_F() [41/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , pixelCoordinateCartesian)
Definition at line 108 of file CartesianCoordinateTests.cc.
TEST_F() [42/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , pixelCoordinateField)
Definition at line 109 of file CartesianCoordinateTests.cc.
TEST_F() [43/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , RelativeCoordinateCartesian)
Definition at line 102 of file CartesianCoordinateTests.cc.
TEST_F() [44/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , RelativeCoordinateField)
Definition at line 103 of file CartesianCoordinateTests.cc.
TEST_F() [45/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , RO3)
Definition at line 95 of file CartesianCoordinateTests.cc.
TEST_F() [46/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , RO5)
Definition at line 95 of file CartesianCoordinateTests.cc.
TEST_F() [47/131]
CGTEST::TEST_F (CartesianCoordinateCPPTests , TO_C)
Definition at line 95 of file CartesianCoordinateTests.cc.
TEST_F() [48/131]
CGTEST::TEST_F (CartesianCoordinateTests , Equality)
Definition at line 65 of file cartesian_coordinate_tests.cc.
References gu_cartesian_coordinate_equals(), and gu_cartesian_coordinate::x.
TEST_F() [49/131]
CGTEST::TEST_F (ConversionsTests , ConvertesFromCartesianToRelativeFromSource)
Definition at line 301 of file conversions_tests.cc.
References cartesian_coord_to_rr_coord_from_source(), gu_relative_coordinate::direction, and gu_relative_coordinate::distance.
TEST_F() [50/131]
CGTEST::TEST_F (ConversionsTests , ConvertsFromCameraToPixelCoordinate)
Definition at line 93 of file conversions_tests.cc.
References cam_coord_to_px_coord().
TEST_F() [51/131]
CGTEST::TEST_F (ConversionsTests , ConvertsFromFieldCoordinateToRelativeCoordinate)
Definition at line 224 of file conversions_tests.cc.
References gu_relative_coordinate::direction, gu_relative_coordinate::distance, and field_coord_to_rr_coord_to_target().
TEST_F() [52/131]
CGTEST::TEST_F (ConversionsTests , ConvertsFromPercentToRelativeCoordinate)
Definition at line 131 of file conversions_tests.cc.
References gu_relative_coordinate::direction, gu_relative_coordinate::distance, GU_NAO_V5_HEAD, and pct_coord_to_rr_coord().
TEST_F() [53/131]
CGTEST::TEST_F (ConversionsTests , ConvertsFromPercentToRelativeCoordinate3)
Definition at line 139 of file conversions_tests.cc.
References gu_relative_coordinate::direction, gu_relative_coordinate::distance, GU_NAO_V5_HEAD, and pct_coord_to_rr_coord().
TEST_F() [54/131]
CGTEST::TEST_F (ConversionsTests , ConvertsFromPixelToCameraCoordinate)
Definition at line 112 of file conversions_tests.cc.
References px_coord_to_cam_coord().
TEST_F() [55/131]
CGTEST::TEST_F (ConversionsTests , ConvertsFromRelativeCoordinateToFieldCoordinate)
Definition at line 182 of file conversions_tests.cc.
References gu_relative_coordinate::direction, gu_field_coordinate::heading, gu_field_coordinate::position, rr_coord_to_field_coord(), gu_cartesian_coordinate::x, and gu_cartesian_coordinate::y.
TEST_F() [56/131]
CGTEST::TEST_F (ConversionsTests , ConvertsFromRelativeCoordinateToPercent)
Definition at line 147 of file conversions_tests.cc.
References GU_NAO_V5_HEAD, rr_coord_to_pct_coord(), gu_percent_coordinate::x, and gu_percent_coordinate::y.
TEST_F() [57/131]
CGTEST::TEST_F (ConversionsTests , ConvertsFromRelativeCoordinateToPercent2)
Definition at line 155 of file conversions_tests.cc.
References GU_NAO_V5_HEAD, rr_coord_to_pct_coord(), gu_percent_coordinate::x, and gu_percent_coordinate::y.
TEST_F() [58/131]
CGTEST::TEST_F (ConversionsTests , ConvertsFromRelativeCoordinateToPercent3)
Definition at line 163 of file conversions_tests.cc.
References GU_NAO_V5_HEAD, rr_coord_to_pct_coord(), gu_percent_coordinate::x, and gu_percent_coordinate::y.
TEST_F() [59/131]
CGTEST::TEST_F (ConversionsTests , ConvertsFromRelativeCoordinateToPercentClamped)
Definition at line 171 of file conversions_tests.cc.
References clamped_rr_coord_to_pct_coord(), gu_percent_coordinate::x, and gu_percent_coordinate::y.
TEST_F() [60/131]
CGTEST::TEST_F (ConversionsTests , ConvertsFromRelativeToCartesianFromSource)
Definition at line 287 of file conversions_tests.cc.
References rr_coord_to_cartesian_coord_from_source(), gu_cartesian_coordinate::x, and gu_cartesian_coordinate::y.
TEST_F() [61/131]
CGTEST::TEST_F (ConversionsTests , ConvertsToCorrectPercentCoordinate)
Definition at line 67 of file conversions_tests.cc.
References px_coord_to_pct_coord().
TEST_F() [62/131]
CGTEST::TEST_F (ConversionsTests , ConvertsToCorrectPixelCoordinate)
Definition at line 80 of file conversions_tests.cc.
References pct_coord_to_px_coord().
TEST_F() [63/131]
CGTEST::TEST_F (ConversionsTests , ConvertsToFieldFromRelativeFromField)
Definition at line 315 of file conversions_tests.cc.
References rr_coord_to_cartesian_coord_from_field(), gu_cartesian_coordinate::x, and gu_cartesian_coordinate::y.
TEST_F() [64/131]
CGTEST::TEST_F (ConversionsTests , ConvertsToRelativeCoordinateFromFieldSource)
Definition at line 200 of file conversions_tests.cc.
References gu_relative_coordinate::direction, gu_field_coordinate::heading, gu_field_coordinate::position, rr_coord_to_field_coord_from_source(), gu_cartesian_coordinate::x, and gu_cartesian_coordinate::y.
TEST_F() [65/131]
CGTEST::TEST_F (ConversionsTests , ConvertsToRelativeFromFieldToTarget)
Definition at line 329 of file conversions_tests.cc.
References gu_relative_coordinate::direction, gu_relative_coordinate::distance, and field_coord_to_rr_coord_to_target().
TEST_F() [66/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , cameraCoordinateCartesian)
Definition at line 118 of file FieldCoordinateTests.cc.
TEST_F() [67/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , cameraCoordinateField)
Definition at line 119 of file FieldCoordinateTests.cc.
TEST_F() [68/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , CartesianCoordinate)
Definition at line 107 of file FieldCoordinateTests.cc.
TEST_F() [69/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , cartesianCoordinateCamera)
Definition at line 100 of file FieldCoordinateTests.cc.
TEST_F() [70/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , cartesianCoordinatePercent)
Definition at line 102 of file FieldCoordinateTests.cc.
TEST_F() [71/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , cartesianCoordinatePixel)
Definition at line 101 of file FieldCoordinateTests.cc.
TEST_F() [72/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , clampedCameraCoordinateCartesian)
Definition at line 127 of file FieldCoordinateTests.cc.
TEST_F() [73/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , clampedCameraCoordinateField)
Definition at line 128 of file FieldCoordinateTests.cc.
TEST_F() [74/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , clampedPercentCoordinateCartesian)
Definition at line 121 of file FieldCoordinateTests.cc.
TEST_F() [75/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , clampedPercentCoordinateField)
Definition at line 122 of file FieldCoordinateTests.cc.
TEST_F() [76/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , clampedPixelCoordinateCartesian)
Definition at line 124 of file FieldCoordinateTests.cc.
TEST_F() [77/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , clampedPixelCoordinateField)
Definition at line 125 of file FieldCoordinateTests.cc.
TEST_F() [78/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , ConvertibleToC)
Definition at line 98 of file FieldCoordinateTests.cc.
TEST_F() [79/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , Equality)
Definition at line 98 of file FieldCoordinateTests.cc.
TEST_F() [80/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , FieldCoordinate)
Definition at line 108 of file FieldCoordinateTests.cc.
TEST_F() [81/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , fieldCoordinateCamera)
Definition at line 103 of file FieldCoordinateTests.cc.
TEST_F() [82/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , fieldCoordinatePercent)
Definition at line 105 of file FieldCoordinateTests.cc.
TEST_F() [83/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , fieldCoordinatePixel)
Definition at line 104 of file FieldCoordinateTests.cc.
TEST_F() [84/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , GettersSetters)
Definition at line 130 of file FieldCoordinateTests.cc.
References GU::FieldCoordinate::heading(), GU::FieldCoordinate::position(), GU::FieldCoordinate::set_heading(), and GU::FieldCoordinate::set_position().
TEST_F() [85/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , percentCoordinateCartesian)
Definition at line 112 of file FieldCoordinateTests.cc.
TEST_F() [86/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , percentCoordinateField)
Definition at line 113 of file FieldCoordinateTests.cc.
TEST_F() [87/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , pixelCoordinateCartesian)
Definition at line 115 of file FieldCoordinateTests.cc.
TEST_F() [88/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , pixelCoordinateField)
Definition at line 116 of file FieldCoordinateTests.cc.
TEST_F() [89/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , RelativeCoordinateToCartesian)
Definition at line 109 of file FieldCoordinateTests.cc.
TEST_F() [90/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , RelativeCoordinateToField)
Definition at line 110 of file FieldCoordinateTests.cc.
TEST_F() [91/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , RO3)
Definition at line 98 of file FieldCoordinateTests.cc.
TEST_F() [92/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , RO5)
Definition at line 98 of file FieldCoordinateTests.cc.
TEST_F() [93/131]
CGTEST::TEST_F (FieldCoordinateCPPTests , TO_C)
Definition at line 98 of file FieldCoordinateTests.cc.
TEST_F() [94/131]
CGTEST::TEST_F (FieldCoordinateTests , Equality)
Definition at line 65 of file field_coordinate_tests.cc.
References gu_field_coordinate_equals(), gu_field_coordinate::position, and gu_cartesian_coordinate::x.
TEST_F() [95/131]
CGTEST::TEST_F (PercentCoordinateCPPTests , CameraCoordinate)
Definition at line 96 of file PercentCoordinateTests.cc.
TEST_F() [96/131]
CGTEST::TEST_F (PercentCoordinateCPPTests , ConvertibleToC)
Definition at line 95 of file PercentCoordinateTests.cc.
TEST_F() [97/131]
CGTEST::TEST_F (PercentCoordinateCPPTests , Equality)
Definition at line 95 of file PercentCoordinateTests.cc.
TEST_F() [98/131]
CGTEST::TEST_F (PercentCoordinateCPPTests , GettersSetters)
Definition at line 100 of file PercentCoordinateTests.cc.
References GU::PercentCoordinate::set_x(), GU::PercentCoordinate::set_y(), GU::PercentCoordinate::x(), and GU::PercentCoordinate::y().
TEST_F() [99/131]
CGTEST::TEST_F (PercentCoordinateCPPTests , PixelCoordinate)
Definition at line 97 of file PercentCoordinateTests.cc.
TEST_F() [100/131]
CGTEST::TEST_F (PercentCoordinateCPPTests , relativeCoordinate)
Definition at line 98 of file PercentCoordinateTests.cc.
TEST_F() [101/131]
CGTEST::TEST_F (PercentCoordinateCPPTests , RO3)
Definition at line 95 of file PercentCoordinateTests.cc.
TEST_F() [102/131]
CGTEST::TEST_F (PercentCoordinateCPPTests , RO5)
Definition at line 95 of file PercentCoordinateTests.cc.
TEST_F() [103/131]
CGTEST::TEST_F (PercentCoordinateCPPTests , TO_C)
Definition at line 95 of file PercentCoordinateTests.cc.
TEST_F() [104/131]
CGTEST::TEST_F (PercentCoordinateTests , Equality)
Definition at line 65 of file percent_coordinate_tests.cc.
References gu_percent_coordinate_equals().
TEST_F() [105/131]
CGTEST::TEST_F (PixelCoordinateCPPTests , CameraCoordinate)
Definition at line 98 of file PixelCoordinateTests.cc.
TEST_F() [106/131]
CGTEST::TEST_F (PixelCoordinateCPPTests , ConvertibleToC)
Definition at line 97 of file PixelCoordinateTests.cc.
TEST_F() [107/131]
CGTEST::TEST_F (PixelCoordinateCPPTests , Equality)
Definition at line 97 of file PixelCoordinateTests.cc.
TEST_F() [108/131]
CGTEST::TEST_F (PixelCoordinateCPPTests , GettersSetters)
Definition at line 102 of file PixelCoordinateTests.cc.
References GU::PixelCoordinate::resHeight(), GU::PixelCoordinate::resWidth(), GU::PixelCoordinate::set_resHeight(), GU::PixelCoordinate::set_resWidth(), GU::PixelCoordinate::set_x(), GU::PixelCoordinate::set_y(), GU::PixelCoordinate::x(), and GU::PixelCoordinate::y().
TEST_F() [109/131]
CGTEST::TEST_F (PixelCoordinateCPPTests , PercentCoordinate)
Definition at line 99 of file PixelCoordinateTests.cc.
TEST_F() [110/131]
CGTEST::TEST_F (PixelCoordinateCPPTests , relativeCoordinate)
Definition at line 100 of file PixelCoordinateTests.cc.
TEST_F() [111/131]
CGTEST::TEST_F (PixelCoordinateCPPTests , RO3)
Definition at line 97 of file PixelCoordinateTests.cc.
TEST_F() [112/131]
CGTEST::TEST_F (PixelCoordinateCPPTests , RO5)
Definition at line 97 of file PixelCoordinateTests.cc.
TEST_F() [113/131]
CGTEST::TEST_F (PixelCoordinateCPPTests , TO_C)
Definition at line 97 of file PixelCoordinateTests.cc.
TEST_F() [114/131]
CGTEST::TEST_F (PixelCoordinateTests , Equality)
Definition at line 65 of file pixel_coordinate_tests.cc.
References gu_pixel_coordinate_equals().
TEST_F() [115/131]
CGTEST::TEST_F (RelativeCoordinateCPPTests , cameraCoordinate)
Definition at line 101 of file RelativeCoordinateTests.cc.
TEST_F() [116/131]
CGTEST::TEST_F (RelativeCoordinateCPPTests , CartesianCoordinate)
Definition at line 97 of file RelativeCoordinateTests.cc.
TEST_F() [117/131]
CGTEST::TEST_F (RelativeCoordinateCPPTests , clampedCameraCoordinate)
Definition at line 105 of file RelativeCoordinateTests.cc.
TEST_F() [118/131]
CGTEST::TEST_F (RelativeCoordinateCPPTests , clampedPercentCoordinate)
Definition at line 107 of file RelativeCoordinateTests.cc.
TEST_F() [119/131]
CGTEST::TEST_F (RelativeCoordinateCPPTests , clampedPixelCoordinate)
Definition at line 106 of file RelativeCoordinateTests.cc.
TEST_F() [120/131]
CGTEST::TEST_F (RelativeCoordinateCPPTests , ConvertibleToC)
Definition at line 95 of file RelativeCoordinateTests.cc.
TEST_F() [121/131]
CGTEST::TEST_F (RelativeCoordinateCPPTests , Equality)
Definition at line 95 of file RelativeCoordinateTests.cc.
TEST_F() [122/131]
CGTEST::TEST_F (RelativeCoordinateCPPTests , FieldCoordinate)
Definition at line 98 of file RelativeCoordinateTests.cc.
TEST_F() [123/131]
CGTEST::TEST_F (RelativeCoordinateCPPTests , GettersSetters)
Definition at line 109 of file RelativeCoordinateTests.cc.
References GU::RelativeCoordinate::direction(), GU::RelativeCoordinate::distance(), GU::RelativeCoordinate::set_direction(), and GU::RelativeCoordinate::set_distance().
TEST_F() [124/131]
CGTEST::TEST_F (RelativeCoordinateCPPTests , percentCoordinate)
Definition at line 103 of file RelativeCoordinateTests.cc.
TEST_F() [125/131]
CGTEST::TEST_F (RelativeCoordinateCPPTests , pixelCoordinate)
Definition at line 102 of file RelativeCoordinateTests.cc.
TEST_F() [126/131]
CGTEST::TEST_F (RelativeCoordinateCPPTests , RelativeCoordinate)
Definition at line 99 of file RelativeCoordinateTests.cc.
TEST_F() [127/131]
CGTEST::TEST_F (RelativeCoordinateCPPTests , RO3)
Definition at line 95 of file RelativeCoordinateTests.cc.
TEST_F() [128/131]
CGTEST::TEST_F (RelativeCoordinateCPPTests , RO5)
Definition at line 95 of file RelativeCoordinateTests.cc.
TEST_F() [129/131]
CGTEST::TEST_F (RelativeCoordinateCPPTests , TO_C)
Definition at line 95 of file RelativeCoordinateTests.cc.
TEST_F() [130/131]
CGTEST::TEST_F (RelativeCoordinateTests , Equality)
Definition at line 65 of file relative_coordinate_tests.cc.
References gu_relative_coordinate_equals().
TEST_F() [131/131]
CGTEST::TEST_F (RobotTests , Equality)
Definition at line 65 of file camera_pivot_tests.cc.
References gu_camera_pivot_equals(), GU_NAO_V5_HEAD, and GU_PEPPER_HEAD.