gucoordinates: percent_coordinate.c File Reference
percent_coordinate.c File Reference
#include "percent_coordinate.h"
#include <math.h>
Functions
bool gu_percent_coordinate_equals (const gu_percent_coordinate lhs, const gu_percent_coordinate rhs, const percent_d tolerance)
percent_d gu_percent_coordinate_x_lower_bound (const gu_percent_coordinate coord)
percent_d gu_percent_coordinate_y_lower_bound (const gu_percent_coordinate coord)
percent_d gu_percent_coordinate_x_upper_bound (const gu_percent_coordinate coord)
percent_d gu_percent_coordinate_y_upper_bound (const gu_percent_coordinate coord)
Function Documentation
gu_percent_coordinate_equals()
bool gu_percent_coordinate_equals (const gu_percent_coordinate lhs, const gu_percent_coordinate rhs, const percent_d tolerance)
Definition at line 62 of file percent_coordinate.c.
References gu_percent_coordinate::x, and gu_percent_coordinate::y.
Referenced by gu_optional_percent_coordinate_equals(), GU::PercentCoordinate::operator==(), and CGTEST::TEST_F().
gu_percent_coordinate_x_lower_bound()
percent_d gu_percent_coordinate_x_lower_bound (const gu_percent_coordinate coord)
Definition at line 69 of file percent_coordinate.c.
Referenced by GU::PercentCoordinate::xLowerBound().
gu_percent_coordinate_x_upper_bound()
percent_d gu_percent_coordinate_x_upper_bound (const gu_percent_coordinate coord)
Definition at line 81 of file percent_coordinate.c.
Referenced by GU::PercentCoordinate::xUpperBound().
gu_percent_coordinate_y_lower_bound()
percent_d gu_percent_coordinate_y_lower_bound (const gu_percent_coordinate coord)
Definition at line 75 of file percent_coordinate.c.
Referenced by GU::PercentCoordinate::yLowerBound().
gu_percent_coordinate_y_upper_bound()
percent_d gu_percent_coordinate_y_upper_bound (const gu_percent_coordinate coord)
Definition at line 87 of file percent_coordinate.c.
Referenced by GU::PercentCoordinate::yUpperBound().