gucoordinates: tests/pixel_coordinate_fakes.h File Reference
pixel_coordinate_fakes.h File Reference
#include "fff.h"
#include "../pixel_coordinate.h"
Classes
struct gu_pixel_coordinate_equals_Fake
struct gu_pixel_coordinate_x_lower_bound_Fake
struct gu_pixel_coordinate_y_lower_bound_Fake
struct gu_pixel_coordinate_x_upper_bound_Fake
struct gu_pixel_coordinate_y_upper_bound_Fake
Macros
#define PIXEL_COORDINATE_FAKES(FAKE)
Typedefs
typedef struct gu_pixel_coordinate_equals_Fake gu_pixel_coordinate_equals_Fake
typedef struct gu_pixel_coordinate_x_lower_bound_Fake gu_pixel_coordinate_x_lower_bound_Fake
typedef struct gu_pixel_coordinate_y_lower_bound_Fake gu_pixel_coordinate_y_lower_bound_Fake
typedef struct gu_pixel_coordinate_x_upper_bound_Fake gu_pixel_coordinate_x_upper_bound_Fake
typedef struct gu_pixel_coordinate_y_upper_bound_Fake gu_pixel_coordinate_y_upper_bound_Fake
Functions
void gu_pixel_coordinate_equals_reset (void)
bool gu_pixel_coordinate_equals (const gu_pixel_coordinate arg0, const gu_pixel_coordinate arg1)
void gu_pixel_coordinate_x_lower_bound_reset (void)
pixels_t gu_pixel_coordinate_x_lower_bound (const gu_pixel_coordinate arg0)
void gu_pixel_coordinate_y_lower_bound_reset (void)
pixels_t gu_pixel_coordinate_y_lower_bound (const gu_pixel_coordinate arg0)
void gu_pixel_coordinate_x_upper_bound_reset (void)
pixels_t gu_pixel_coordinate_x_upper_bound (const gu_pixel_coordinate arg0)
void gu_pixel_coordinate_y_upper_bound_reset (void)
pixels_t gu_pixel_coordinate_y_upper_bound (const gu_pixel_coordinate arg0)
Variables
gu_pixel_coordinate_equals_Fake gu_pixel_coordinate_equals_fake
gu_pixel_coordinate_x_lower_bound_Fake gu_pixel_coordinate_x_lower_bound_fake
gu_pixel_coordinate_y_lower_bound_Fake gu_pixel_coordinate_y_lower_bound_fake
gu_pixel_coordinate_x_upper_bound_Fake gu_pixel_coordinate_x_upper_bound_fake
gu_pixel_coordinate_y_upper_bound_Fake gu_pixel_coordinate_y_upper_bound_fake
Macro Definition Documentation
PIXEL_COORDINATE_FAKES
#define PIXEL_COORDINATE_FAKES (FAKE)
Value:
    FAKE(gu_pixel_coordinate_equals) \
    FAKE(gu_pixel_coordinate_x_lower_bound) \
    FAKE(gu_pixel_coordinate_y_lower_bound) \
    FAKE(gu_pixel_coordinate_x_upper_bound) \
    FAKE(gu_pixel_coordinate_y_upper_bound)
Definition at line 69 of file pixel_coordinate_fakes.h.
Typedef Documentation
gu_pixel_coordinate_equals_Fake
typedef struct gu_pixel_coordinate_equals_Fake gu_pixel_coordinate_equals_Fake
gu_pixel_coordinate_x_lower_bound_Fake
typedef struct gu_pixel_coordinate_x_lower_bound_Fake gu_pixel_coordinate_x_lower_bound_Fake
gu_pixel_coordinate_x_upper_bound_Fake
typedef struct gu_pixel_coordinate_x_upper_bound_Fake gu_pixel_coordinate_x_upper_bound_Fake
gu_pixel_coordinate_y_lower_bound_Fake
typedef struct gu_pixel_coordinate_y_lower_bound_Fake gu_pixel_coordinate_y_lower_bound_Fake
gu_pixel_coordinate_y_upper_bound_Fake
typedef struct gu_pixel_coordinate_y_upper_bound_Fake gu_pixel_coordinate_y_upper_bound_Fake
Function Documentation
gu_pixel_coordinate_equals()
bool gu_pixel_coordinate_equals (const gu_pixel_coordinate arg0, const gu_pixel_coordinate arg1)
Definition at line 64 of file pixel_coordinate.c.
References gu_pixel_coordinate::res_height, gu_pixel_coordinate::res_width, gu_pixel_coordinate::x, and gu_pixel_coordinate::y.
Referenced by gu_optional_pixel_coordinate_equals(), GU::PixelCoordinate::operator==(), and CGTEST::TEST_F().
gu_pixel_coordinate_equals_reset()
void gu_pixel_coordinate_equals_reset (void)
Definition at line 63 of file pixel_coordinate_fakes.c.
gu_pixel_coordinate_x_lower_bound()
pixels_t gu_pixel_coordinate_x_lower_bound (const gu_pixel_coordinate arg0)
Definition at line 72 of file pixel_coordinate.c.
References gu_pixel_coordinate::res_width.
Referenced by GU::PixelCoordinate::xLowerBound().
gu_pixel_coordinate_x_lower_bound_reset()
void gu_pixel_coordinate_x_lower_bound_reset (void)
Definition at line 64 of file pixel_coordinate_fakes.c.
gu_pixel_coordinate_x_upper_bound()
pixels_t gu_pixel_coordinate_x_upper_bound (const gu_pixel_coordinate arg0)
Definition at line 82 of file pixel_coordinate.c.
References gu_pixel_coordinate::res_width.
Referenced by GU::PixelCoordinate::xUpperBound().
gu_pixel_coordinate_x_upper_bound_reset()
void gu_pixel_coordinate_x_upper_bound_reset (void)
Definition at line 66 of file pixel_coordinate_fakes.c.
gu_pixel_coordinate_y_lower_bound()
pixels_t gu_pixel_coordinate_y_lower_bound (const gu_pixel_coordinate arg0)
Definition at line 77 of file pixel_coordinate.c.
References gu_pixel_coordinate::res_height.
Referenced by GU::PixelCoordinate::yLowerBound().
gu_pixel_coordinate_y_lower_bound_reset()
void gu_pixel_coordinate_y_lower_bound_reset (void)
Definition at line 65 of file pixel_coordinate_fakes.c.
gu_pixel_coordinate_y_upper_bound()
pixels_t gu_pixel_coordinate_y_upper_bound (const gu_pixel_coordinate arg0)
Definition at line 87 of file pixel_coordinate.c.
References gu_pixel_coordinate::res_height.
Referenced by GU::PixelCoordinate::yUpperBound().
gu_pixel_coordinate_y_upper_bound_reset()
void gu_pixel_coordinate_y_upper_bound_reset (void)
Definition at line 67 of file pixel_coordinate_fakes.c.
Variable Documentation
gu_pixel_coordinate_equals_fake
gu_pixel_coordinate_equals_Fake gu_pixel_coordinate_equals_fake extern
Definition at line 63 of file pixel_coordinate_fakes.c.
gu_pixel_coordinate_x_lower_bound_fake
gu_pixel_coordinate_x_lower_bound_Fake gu_pixel_coordinate_x_lower_bound_fake extern
Definition at line 64 of file pixel_coordinate_fakes.c.
gu_pixel_coordinate_x_upper_bound_fake
gu_pixel_coordinate_x_upper_bound_Fake gu_pixel_coordinate_x_upper_bound_fake extern
Definition at line 66 of file pixel_coordinate_fakes.c.
gu_pixel_coordinate_y_lower_bound_fake
gu_pixel_coordinate_y_lower_bound_Fake gu_pixel_coordinate_y_lower_bound_fake extern
Definition at line 65 of file pixel_coordinate_fakes.c.
gu_pixel_coordinate_y_upper_bound_fake
gu_pixel_coordinate_y_upper_bound_Fake gu_pixel_coordinate_y_upper_bound_fake extern
Definition at line 67 of file pixel_coordinate_fakes.c.