gucoordinates: pixel_coordinate.c File Reference
pixel_coordinate.c File Reference
#include "pixel_coordinate.h"
#include <stdbool.h>
#include <math.h>
Functions
bool gu_pixel_coordinate_equals (const gu_pixel_coordinate lhs, const gu_pixel_coordinate rhs)
pixels_t gu_pixel_coordinate_x_lower_bound (const gu_pixel_coordinate coord)
pixels_t gu_pixel_coordinate_y_lower_bound (const gu_pixel_coordinate coord)
pixels_t gu_pixel_coordinate_x_upper_bound (const gu_pixel_coordinate coord)
pixels_t gu_pixel_coordinate_y_upper_bound (const gu_pixel_coordinate coord)
Function Documentation
gu_pixel_coordinate_equals()
bool gu_pixel_coordinate_equals (const gu_pixel_coordinate lhs, const gu_pixel_coordinate rhs)
Definition at line 64 of file pixel_coordinate.c.
References gu_pixel_coordinate::res_height, gu_pixel_coordinate::res_width, gu_pixel_coordinate::x, and gu_pixel_coordinate::y.
Referenced by gu_optional_pixel_coordinate_equals(), GU::PixelCoordinate::operator==(), and CGTEST::TEST_F().
gu_pixel_coordinate_x_lower_bound()
pixels_t gu_pixel_coordinate_x_lower_bound (const gu_pixel_coordinate coord)
Definition at line 72 of file pixel_coordinate.c.
References gu_pixel_coordinate::res_width.
Referenced by GU::PixelCoordinate::xLowerBound().
gu_pixel_coordinate_x_upper_bound()
pixels_t gu_pixel_coordinate_x_upper_bound (const gu_pixel_coordinate coord)
Definition at line 82 of file pixel_coordinate.c.
References gu_pixel_coordinate::res_width.
Referenced by GU::PixelCoordinate::xUpperBound().
gu_pixel_coordinate_y_lower_bound()
pixels_t gu_pixel_coordinate_y_lower_bound (const gu_pixel_coordinate coord)
Definition at line 77 of file pixel_coordinate.c.
References gu_pixel_coordinate::res_height.
Referenced by GU::PixelCoordinate::yLowerBound().
gu_pixel_coordinate_y_upper_bound()
pixels_t gu_pixel_coordinate_y_upper_bound (const gu_pixel_coordinate coord)
Definition at line 87 of file pixel_coordinate.c.
References gu_pixel_coordinate::res_height.
Referenced by GU::PixelCoordinate::yUpperBound().