gucoordinates: GU::PercentCoordinate Struct Reference
GU::PercentCoordinate Struct Reference
#include <PercentCoordinate.hpp>
Public Member Functions
PercentCoordinate () NOEXCEPT
PercentCoordinate (percent_d, percent_d) NOEXCEPT
PercentCoordinate (const PercentCoordinate &other) NOEXCEPT
PercentCoordinate (const gu_percent_coordinate &other) NOEXCEPT
PercentCoordinate (PercentCoordinate &&other) NOEXCEPT
PercentCoordinate (gu_percent_coordinate &&other) NOEXCEPT
~PercentCoordinate () NOEXCEPT
PercentCoordinate & operator= (const PercentCoordinate &other) NOEXCEPT
PercentCoordinate & operator= (const gu_percent_coordinate &other) NOEXCEPT
PercentCoordinate & operator= (PercentCoordinate &&other) NOEXCEPT
PercentCoordinate & operator= (gu_percent_coordinate &&other) NOEXCEPT
CameraCoordinate cameraCoordinate (const pixels_u, const pixels_u) const NOEXCEPT
PixelCoordinate pixelCoordinate (const pixels_u, const pixels_u) const NOEXCEPT
RelativeCoordinate relativeCoordinate (const GU::CameraPivot &, const int) const NOEXCEPT
percent_d x () const NOEXCEPT
void set_x (const percent_d) NOEXCEPT
percent_d y () const NOEXCEPT
void set_y (const percent_d) NOEXCEPT
percent_d xLowerBound () const NOEXCEPT
percent_d xUpperBound () const NOEXCEPT
percent_d yLowerBound () const NOEXCEPT
percent_d yUpperBound () const NOEXCEPT
bool operator== (const PercentCoordinate &other) const NOEXCEPT
bool operator!= (const PercentCoordinate &other) const NOEXCEPT
bool operator== (const gu_percent_coordinate &other) const NOEXCEPT
bool operator!= (const gu_percent_coordinate &other) const NOEXCEPT
Additional Inherited Members
Public Attributes inherited from gu_percent_coordinate
percent_d x
The x coordinate of the pixel within the image as a percentage.
percent_d y
The y coordinate of the pixel within the image as a percentage.
Detailed Description
Definition at line 79 of file PercentCoordinate.hpp.
Constructor & Destructor Documentation
PercentCoordinate() [1/6]
GU::PercentCoordinate::PercentCoordinate ()
Definition at line 66 of file PercentCoordinate.cc.
PercentCoordinate() [2/6]
GU::PercentCoordinate::PercentCoordinate (percent_d t_x, percent_d t_y)
Definition at line 68 of file PercentCoordinate.cc.
PercentCoordinate() [3/6]
GU::PercentCoordinate::PercentCoordinate (const PercentCoordinate & other)
Definition at line 74 of file PercentCoordinate.cc.
PercentCoordinate() [4/6]
GU::PercentCoordinate::PercentCoordinate (const gu_percent_coordinate & other)
Definition at line 80 of file PercentCoordinate.cc.
PercentCoordinate() [5/6]
GU::PercentCoordinate::PercentCoordinate (PercentCoordinate && other)
Definition at line 87 of file PercentCoordinate.cc.
PercentCoordinate() [6/6]
GU::PercentCoordinate::PercentCoordinate (gu_percent_coordinate && other)
Definition at line 93 of file PercentCoordinate.cc.
~PercentCoordinate()
GU::PercentCoordinate::~PercentCoordinate ()
Definition at line 100 of file PercentCoordinate.cc.
Member Function Documentation
cameraCoordinate()
GU::CameraCoordinate GU::PercentCoordinate::cameraCoordinate (const pixels_u resWidth, const pixels_u resHeight) const
Definition at line 151 of file PercentCoordinate.cc.
operator!=() [1/2]
bool GU::PercentCoordinate::operator!= (const gu_percent_coordinate & other) const
Definition at line 216 of file PercentCoordinate.cc.
operator!=() [2/2]
bool GU::PercentCoordinate::operator!= (const PercentCoordinate & other) const
Definition at line 206 of file PercentCoordinate.cc.
operator=() [1/4]
GU::PercentCoordinate & GU::PercentCoordinate::operator= (const gu_percent_coordinate & other)
Definition at line 113 of file PercentCoordinate.cc.
operator=() [2/4]
GU::PercentCoordinate & GU::PercentCoordinate::operator= (const PercentCoordinate & other)
Definition at line 102 of file PercentCoordinate.cc.
operator=() [3/4]
GU::PercentCoordinate & GU::PercentCoordinate::operator= (gu_percent_coordinate && other)
Definition at line 135 of file PercentCoordinate.cc.
operator=() [4/4]
GU::PercentCoordinate & GU::PercentCoordinate::operator= (PercentCoordinate && other)
Definition at line 125 of file PercentCoordinate.cc.
operator==() [1/2]
bool GU::PercentCoordinate::operator== (const gu_percent_coordinate & other) const
Definition at line 211 of file PercentCoordinate.cc.
References gu_percent_coordinate_equals().
operator==() [2/2]
bool GU::PercentCoordinate::operator== (const PercentCoordinate & other) const
Definition at line 201 of file PercentCoordinate.cc.
References gu_percent_coordinate_equals().
pixelCoordinate()
GU::PixelCoordinate GU::PercentCoordinate::pixelCoordinate (const pixels_u resWidth, const pixels_u resHeight) const
Definition at line 146 of file PercentCoordinate.cc.
References pct_coord_to_px_coord().
relativeCoordinate()
GU::RelativeCoordinate GU::PercentCoordinate::relativeCoordinate (const GU::CameraPivot & cameraPivot, const int cameraOffset) const
Definition at line 156 of file PercentCoordinate.cc.
References pct_coord_to_rr_coord().
set_x()
void GU::PercentCoordinate::set_x (const percent_d newValue)
Definition at line 166 of file PercentCoordinate.cc.
References gu_percent_coordinate::x.
Referenced by CGTEST::PercentCoordinateCPPTests::change(), and CGTEST::TEST_F().
set_y()
void GU::PercentCoordinate::set_y (const percent_d newValue)
Definition at line 176 of file PercentCoordinate.cc.
References gu_percent_coordinate::y.
Referenced by CGTEST::TEST_F().
x()
percent_d GU::PercentCoordinate::x () const
Definition at line 161 of file PercentCoordinate.cc.
References gu_percent_coordinate::x.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
xLowerBound()
percent_d GU::PercentCoordinate::xLowerBound () const
Definition at line 181 of file PercentCoordinate.cc.
References gu_percent_coordinate_x_lower_bound().
xUpperBound()
percent_d GU::PercentCoordinate::xUpperBound () const
Definition at line 186 of file PercentCoordinate.cc.
References gu_percent_coordinate_x_upper_bound().
y()
percent_d GU::PercentCoordinate::y () const
Definition at line 171 of file PercentCoordinate.cc.
References gu_percent_coordinate::y.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
yLowerBound()
percent_d GU::PercentCoordinate::yLowerBound () const
Definition at line 191 of file PercentCoordinate.cc.
References gu_percent_coordinate_y_lower_bound().
yUpperBound()
percent_d GU::PercentCoordinate::yUpperBound () const
Definition at line 196 of file PercentCoordinate.cc.
References gu_percent_coordinate_y_upper_bound().
The documentation for this struct was generated from the following files:
PercentCoordinate.hpp
PercentCoordinate.cc