gucoordinates: GU::FieldCoordinate Struct Reference
GU::FieldCoordinate Struct Reference
#include <FieldCoordinate.hpp>
Public Member Functions
FieldCoordinate () NOEXCEPT
FieldCoordinate (CartesianCoordinate, degrees_t) NOEXCEPT
FieldCoordinate (const FieldCoordinate &other) NOEXCEPT
FieldCoordinate (const gu_field_coordinate &other) NOEXCEPT
FieldCoordinate (FieldCoordinate &&other) NOEXCEPT
FieldCoordinate (gu_field_coordinate &&other) NOEXCEPT
~FieldCoordinate () NOEXCEPT
FieldCoordinate & operator= (const FieldCoordinate &other) NOEXCEPT
FieldCoordinate & operator= (const gu_field_coordinate &other) NOEXCEPT
FieldCoordinate & operator= (FieldCoordinate &&other) NOEXCEPT
FieldCoordinate & operator= (gu_field_coordinate &&other) NOEXCEPT
CartesianCoordinate cartesianCoordinateAt (const GU::RelativeCoordinate &) const NOEXCEPT
FieldCoordinate fieldCoordinateAt (const GU::RelativeCoordinate &, const degrees_t) const NOEXCEPT
RelativeCoordinate relativeCoordinateTo (const GU::CartesianCoordinate &) const NOEXCEPT
RelativeCoordinate relativeCoordinateTo (const GU::FieldCoordinate &) const NOEXCEPT
CartesianCoordinate cartesianCoordinateAt (const GU::CameraCoordinate &, const GU::CameraPivot &, const int) const NOEXCEPT
CartesianCoordinate cartesianCoordinateAt (const GU::PixelCoordinate &, const GU::CameraPivot &, const int) const NOEXCEPT
CartesianCoordinate cartesianCoordinateAt (const GU::PercentCoordinate &, const GU::CameraPivot &, const int) const NOEXCEPT
FieldCoordinate fieldCoordinateAt (const GU::CameraCoordinate &, const GU::CameraPivot &, const int, const degrees_t) const NOEXCEPT
FieldCoordinate fieldCoordinateAt (const GU::PixelCoordinate &, const GU::CameraPivot &, const int, const degrees_t) const NOEXCEPT
FieldCoordinate fieldCoordinateAt (const GU::PercentCoordinate &, const GU::CameraPivot &, const int, const degrees_t) const NOEXCEPT
CameraCoordinate cameraCoordinateTo (const GU::CartesianCoordinate &, const GU::CameraPivot &, const int, const pixels_u, const pixels_u) const NOEXCEPT
CameraCoordinate cameraCoordinateTo (const GU::FieldCoordinate &, const GU::CameraPivot &, const int, const pixels_u, const pixels_u) const NOEXCEPT
PixelCoordinate pixelCoordinateTo (const GU::CartesianCoordinate &, const GU::CameraPivot &, const int, const pixels_u, const pixels_u) const NOEXCEPT
PixelCoordinate pixelCoordinateTo (const GU::FieldCoordinate &, const GU::CameraPivot &, const int, const pixels_u, const pixels_u) const NOEXCEPT
PercentCoordinate percentCoordinateTo (const GU::CartesianCoordinate &, const GU::CameraPivot &, const int) const NOEXCEPT
PercentCoordinate percentCoordinateTo (const GU::FieldCoordinate &, const GU::CameraPivot &, const int) const NOEXCEPT
CameraCoordinate clampedCameraCoordinateTo (const GU::CartesianCoordinate &, const GU::CameraPivot &, const int, const pixels_u, const pixels_u) const NOEXCEPT
CameraCoordinate clampedCameraCoordinateTo (const GU::FieldCoordinate &, const GU::CameraPivot &, const int, const pixels_u, const pixels_u) const NOEXCEPT
PixelCoordinate clampedPixelCoordinateTo (const GU::CartesianCoordinate &, const GU::CameraPivot &, const int, const pixels_u, const pixels_u) const NOEXCEPT
PixelCoordinate clampedPixelCoordinateTo (const GU::FieldCoordinate &, const GU::CameraPivot &, const int, const pixels_u, const pixels_u) const NOEXCEPT
PercentCoordinate clampedPercentCoordinateTo (const GU::CartesianCoordinate &, const GU::CameraPivot &, const int) const NOEXCEPT
PercentCoordinate clampedPercentCoordinateTo (const GU::FieldCoordinate &, const GU::CameraPivot &, const int) const NOEXCEPT
CartesianCoordinate position () const NOEXCEPT
void set_position (const CartesianCoordinate) NOEXCEPT
degrees_t heading () const NOEXCEPT
void set_heading (const degrees_t) NOEXCEPT
bool operator== (const FieldCoordinate &other) const NOEXCEPT
bool operator!= (const FieldCoordinate &other) const NOEXCEPT
bool operator== (const gu_field_coordinate &other) const NOEXCEPT
bool operator!= (const gu_field_coordinate &other) const NOEXCEPT
Additional Inherited Members
Public Attributes inherited from gu_field_coordinate
gu_cartesian_coordinate position
The position of the object on the field.
degrees_t heading
The direction where the object is facing.
Detailed Description
Definition at line 94 of file FieldCoordinate.hpp.
Constructor & Destructor Documentation
FieldCoordinate() [1/6]
GU::FieldCoordinate::FieldCoordinate ()
Definition at line 66 of file FieldCoordinate.cc.
FieldCoordinate() [2/6]
GU::FieldCoordinate::FieldCoordinate (GU::CartesianCoordinate t_position, degrees_t t_heading)
Definition at line 68 of file FieldCoordinate.cc.
FieldCoordinate() [3/6]
GU::FieldCoordinate::FieldCoordinate (const FieldCoordinate & other)
Definition at line 74 of file FieldCoordinate.cc.
FieldCoordinate() [4/6]
GU::FieldCoordinate::FieldCoordinate (const gu_field_coordinate & other)
Definition at line 80 of file FieldCoordinate.cc.
FieldCoordinate() [5/6]
GU::FieldCoordinate::FieldCoordinate (FieldCoordinate && other)
Definition at line 87 of file FieldCoordinate.cc.
FieldCoordinate() [6/6]
GU::FieldCoordinate::FieldCoordinate (gu_field_coordinate && other)
Definition at line 93 of file FieldCoordinate.cc.
~FieldCoordinate()
GU::FieldCoordinate::~FieldCoordinate ()
Definition at line 100 of file FieldCoordinate.cc.
Member Function Documentation
cameraCoordinateTo() [1/2]
GU::CameraCoordinate GU::FieldCoordinate::cameraCoordinateTo (const GU::CartesianCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset, const pixels_u resWidth, const pixels_u resHeight) const
Definition at line 196 of file FieldCoordinate.cc.
cameraCoordinateTo() [2/2]
GU::CameraCoordinate GU::FieldCoordinate::cameraCoordinateTo (const GU::FieldCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset, const pixels_u resWidth, const pixels_u resHeight) const
Definition at line 201 of file FieldCoordinate.cc.
cartesianCoordinateAt() [1/4]
GU::CartesianCoordinate GU::FieldCoordinate::cartesianCoordinateAt (const GU::CameraCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset) const
Definition at line 146 of file FieldCoordinate.cc.
cartesianCoordinateAt() [2/4]
GU::CartesianCoordinate GU::FieldCoordinate::cartesianCoordinateAt (const GU::PercentCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset) const
Definition at line 156 of file FieldCoordinate.cc.
cartesianCoordinateAt() [3/4]
GU::CartesianCoordinate GU::FieldCoordinate::cartesianCoordinateAt (const GU::PixelCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset) const
Definition at line 151 of file FieldCoordinate.cc.
cartesianCoordinateAt() [4/4]
GU::CartesianCoordinate GU::FieldCoordinate::cartesianCoordinateAt (const GU::RelativeCoordinate & target) const
Definition at line 176 of file FieldCoordinate.cc.
References rr_coord_to_cartesian_coord_from_field().
clampedCameraCoordinateTo() [1/2]
GU::CameraCoordinate GU::FieldCoordinate::clampedCameraCoordinateTo (const GU::CartesianCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset, const pixels_u resWidth, const pixels_u resHeight) const
Definition at line 226 of file FieldCoordinate.cc.
clampedCameraCoordinateTo() [2/2]
GU::CameraCoordinate GU::FieldCoordinate::clampedCameraCoordinateTo (const GU::FieldCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset, const pixels_u resWidth, const pixels_u resHeight) const
Definition at line 231 of file FieldCoordinate.cc.
clampedPercentCoordinateTo() [1/2]
GU::PercentCoordinate GU::FieldCoordinate::clampedPercentCoordinateTo (const GU::CartesianCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset) const
Definition at line 246 of file FieldCoordinate.cc.
clampedPercentCoordinateTo() [2/2]
GU::PercentCoordinate GU::FieldCoordinate::clampedPercentCoordinateTo (const GU::FieldCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset) const
Definition at line 251 of file FieldCoordinate.cc.
clampedPixelCoordinateTo() [1/2]
GU::PixelCoordinate GU::FieldCoordinate::clampedPixelCoordinateTo (const GU::CartesianCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset, const pixels_u resWidth, const pixels_u resHeight) const
Definition at line 236 of file FieldCoordinate.cc.
clampedPixelCoordinateTo() [2/2]
GU::PixelCoordinate GU::FieldCoordinate::clampedPixelCoordinateTo (const GU::FieldCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset, const pixels_u resWidth, const pixels_u resHeight) const
Definition at line 241 of file FieldCoordinate.cc.
fieldCoordinateAt() [1/4]
GU::FieldCoordinate GU::FieldCoordinate::fieldCoordinateAt (const GU::CameraCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset, const degrees_t targetHeading) const
Definition at line 161 of file FieldCoordinate.cc.
fieldCoordinateAt() [2/4]
GU::FieldCoordinate GU::FieldCoordinate::fieldCoordinateAt (const GU::PercentCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset, const degrees_t targetHeading) const
Definition at line 171 of file FieldCoordinate.cc.
fieldCoordinateAt() [3/4]
GU::FieldCoordinate GU::FieldCoordinate::fieldCoordinateAt (const GU::PixelCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset, const degrees_t targetHeading) const
Definition at line 166 of file FieldCoordinate.cc.
fieldCoordinateAt() [4/4]
GU::FieldCoordinate GU::FieldCoordinate::fieldCoordinateAt (const GU::RelativeCoordinate & target, const degrees_t targetHeading) const
Definition at line 181 of file FieldCoordinate.cc.
References rr_coord_to_field_coord_from_source().
heading()
degrees_t GU::FieldCoordinate::heading () const
Definition at line 266 of file FieldCoordinate.cc.
References gu_field_coordinate::heading.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
operator!=() [1/2]
bool GU::FieldCoordinate::operator!= (const FieldCoordinate & other) const
Definition at line 281 of file FieldCoordinate.cc.
operator!=() [2/2]
bool GU::FieldCoordinate::operator!= (const gu_field_coordinate & other) const
Definition at line 291 of file FieldCoordinate.cc.
operator=() [1/4]
GU::FieldCoordinate & GU::FieldCoordinate::operator= (const FieldCoordinate & other)
Definition at line 102 of file FieldCoordinate.cc.
operator=() [2/4]
GU::FieldCoordinate & GU::FieldCoordinate::operator= (const gu_field_coordinate & other)
Definition at line 113 of file FieldCoordinate.cc.
operator=() [3/4]
GU::FieldCoordinate & GU::FieldCoordinate::operator= (FieldCoordinate && other)
Definition at line 125 of file FieldCoordinate.cc.
operator=() [4/4]
GU::FieldCoordinate & GU::FieldCoordinate::operator= (gu_field_coordinate && other)
Definition at line 135 of file FieldCoordinate.cc.
operator==() [1/2]
bool GU::FieldCoordinate::operator== (const FieldCoordinate & other) const
Definition at line 276 of file FieldCoordinate.cc.
References gu_field_coordinate_equals().
operator==() [2/2]
bool GU::FieldCoordinate::operator== (const gu_field_coordinate & other) const
Definition at line 286 of file FieldCoordinate.cc.
References gu_field_coordinate_equals().
percentCoordinateTo() [1/2]
GU::PercentCoordinate GU::FieldCoordinate::percentCoordinateTo (const GU::CartesianCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset) const
Definition at line 216 of file FieldCoordinate.cc.
percentCoordinateTo() [2/2]
GU::PercentCoordinate GU::FieldCoordinate::percentCoordinateTo (const GU::FieldCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset) const
Definition at line 221 of file FieldCoordinate.cc.
pixelCoordinateTo() [1/2]
GU::PixelCoordinate GU::FieldCoordinate::pixelCoordinateTo (const GU::CartesianCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset, const pixels_u resWidth, const pixels_u resHeight) const
Definition at line 206 of file FieldCoordinate.cc.
pixelCoordinateTo() [2/2]
GU::PixelCoordinate GU::FieldCoordinate::pixelCoordinateTo (const GU::FieldCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset, const pixels_u resWidth, const pixels_u resHeight) const
Definition at line 211 of file FieldCoordinate.cc.
position()
GU::CartesianCoordinate GU::FieldCoordinate::position () const
Definition at line 256 of file FieldCoordinate.cc.
References gu_field_coordinate::position.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
relativeCoordinateTo() [1/2]
GU::RelativeCoordinate GU::FieldCoordinate::relativeCoordinateTo (const GU::CartesianCoordinate & target) const
Definition at line 186 of file FieldCoordinate.cc.
References field_coord_to_rr_coord_to_target().
relativeCoordinateTo() [2/2]
GU::RelativeCoordinate GU::FieldCoordinate::relativeCoordinateTo (const GU::FieldCoordinate & target) const
Definition at line 191 of file FieldCoordinate.cc.
set_heading()
void GU::FieldCoordinate::set_heading (const degrees_t newValue)
Definition at line 271 of file FieldCoordinate.cc.
References gu_field_coordinate::heading.
Referenced by CGTEST::TEST_F().
set_position()
void GU::FieldCoordinate::set_position (const CartesianCoordinate)
Definition at line 261 of file FieldCoordinate.cc.
References gu_field_coordinate::position.
Referenced by CGTEST::FieldCoordinateCPPTests::change(), and CGTEST::TEST_F().
The documentation for this struct was generated from the following files:
FieldCoordinate.hpp
FieldCoordinate.cc