gucoordinates: GU::PixelCoordinate Struct Reference
GU::PixelCoordinate Struct Reference
#include <PixelCoordinate.hpp>
Public Member Functions
PixelCoordinate () NOEXCEPT
PixelCoordinate (pixels_t, pixels_t, pixels_u, pixels_u) NOEXCEPT
PixelCoordinate (const PixelCoordinate &other) NOEXCEPT
PixelCoordinate (const gu_pixel_coordinate &other) NOEXCEPT
PixelCoordinate (PixelCoordinate &&other) NOEXCEPT
PixelCoordinate (gu_pixel_coordinate &&other) NOEXCEPT
~PixelCoordinate () NOEXCEPT
PixelCoordinate & operator= (const PixelCoordinate &other) NOEXCEPT
PixelCoordinate & operator= (const gu_pixel_coordinate &other) NOEXCEPT
PixelCoordinate & operator= (PixelCoordinate &&other) NOEXCEPT
PixelCoordinate & operator= (gu_pixel_coordinate &&other) NOEXCEPT
CameraCoordinate cameraCoordinate () const NOEXCEPT
PercentCoordinate percentCoordinate () const NOEXCEPT
RelativeCoordinate relativeCoordinate (const GU::CameraPivot &, const int) const NOEXCEPT
pixels_t x () const NOEXCEPT
void set_x (const pixels_t) NOEXCEPT
pixels_t y () const NOEXCEPT
void set_y (const pixels_t) NOEXCEPT
pixels_u resWidth () const NOEXCEPT
void set_resWidth (const pixels_u) NOEXCEPT
pixels_u resHeight () const NOEXCEPT
void set_resHeight (const pixels_u) NOEXCEPT
pixels_t xLowerBound () const NOEXCEPT
pixels_t xUpperBound () const NOEXCEPT
pixels_t yLowerBound () const NOEXCEPT
pixels_t yUpperBound () const NOEXCEPT
bool operator== (const PixelCoordinate &other) const NOEXCEPT
bool operator!= (const PixelCoordinate &other) const NOEXCEPT
bool operator== (const gu_pixel_coordinate &other) const NOEXCEPT
bool operator!= (const gu_pixel_coordinate &other) const NOEXCEPT
Additional Inherited Members
Public Attributes inherited from gu_pixel_coordinate
pixels_t x
The x coordinate of the pixel within the image.
pixels_t y
The y coordinate of the pixel within the image.
pixels_u res_width
The width of the resolution of the image.
pixels_u res_height
The height of the resolution of the image.
Detailed Description
Definition at line 83 of file PixelCoordinate.hpp.
Constructor & Destructor Documentation
PixelCoordinate() [1/6]
GU::PixelCoordinate::PixelCoordinate ()
Definition at line 66 of file PixelCoordinate.cc.
PixelCoordinate() [2/6]
GU::PixelCoordinate::PixelCoordinate (pixels_t t_x, pixels_t t_y, pixels_u t_resWidth, pixels_u t_resHeight)
Definition at line 68 of file PixelCoordinate.cc.
PixelCoordinate() [3/6]
GU::PixelCoordinate::PixelCoordinate (const PixelCoordinate & other)
Definition at line 76 of file PixelCoordinate.cc.
PixelCoordinate() [4/6]
GU::PixelCoordinate::PixelCoordinate (const gu_pixel_coordinate & other)
Definition at line 84 of file PixelCoordinate.cc.
PixelCoordinate() [5/6]
GU::PixelCoordinate::PixelCoordinate (PixelCoordinate && other)
Definition at line 93 of file PixelCoordinate.cc.
PixelCoordinate() [6/6]
GU::PixelCoordinate::PixelCoordinate (gu_pixel_coordinate && other)
Definition at line 101 of file PixelCoordinate.cc.
~PixelCoordinate()
GU::PixelCoordinate::~PixelCoordinate ()
Definition at line 110 of file PixelCoordinate.cc.
Member Function Documentation
cameraCoordinate()
GU::CameraCoordinate GU::PixelCoordinate::cameraCoordinate () const
Definition at line 164 of file PixelCoordinate.cc.
References px_coord_to_cam_coord().
operator!=() [1/2]
bool GU::PixelCoordinate::operator!= (const gu_pixel_coordinate & other) const
Definition at line 254 of file PixelCoordinate.cc.
operator!=() [2/2]
bool GU::PixelCoordinate::operator!= (const PixelCoordinate & other) const
Definition at line 244 of file PixelCoordinate.cc.
operator=() [1/4]
GU::PixelCoordinate & GU::PixelCoordinate::operator= (const gu_pixel_coordinate & other)
Definition at line 125 of file PixelCoordinate.cc.
operator=() [2/4]
GU::PixelCoordinate & GU::PixelCoordinate::operator= (const PixelCoordinate & other)
Definition at line 112 of file PixelCoordinate.cc.
operator=() [3/4]
GU::PixelCoordinate & GU::PixelCoordinate::operator= (gu_pixel_coordinate && other)
Definition at line 151 of file PixelCoordinate.cc.
operator=() [4/4]
GU::PixelCoordinate & GU::PixelCoordinate::operator= (PixelCoordinate && other)
Definition at line 139 of file PixelCoordinate.cc.
operator==() [1/2]
bool GU::PixelCoordinate::operator== (const gu_pixel_coordinate & other) const
Definition at line 249 of file PixelCoordinate.cc.
References gu_pixel_coordinate_equals().
operator==() [2/2]
bool GU::PixelCoordinate::operator== (const PixelCoordinate & other) const
Definition at line 239 of file PixelCoordinate.cc.
References gu_pixel_coordinate_equals().
percentCoordinate()
GU::PercentCoordinate GU::PixelCoordinate::percentCoordinate () const
Definition at line 169 of file PixelCoordinate.cc.
References px_coord_to_pct_coord().
relativeCoordinate()
GU::RelativeCoordinate GU::PixelCoordinate::relativeCoordinate (const GU::CameraPivot & cameraPivot, const int cameraOffset) const
Definition at line 174 of file PixelCoordinate.cc.
resHeight()
pixels_u GU::PixelCoordinate::resHeight () const
Definition at line 209 of file PixelCoordinate.cc.
References gu_pixel_coordinate::res_height.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
resWidth()
pixels_u GU::PixelCoordinate::resWidth () const
Definition at line 199 of file PixelCoordinate.cc.
References gu_pixel_coordinate::res_width.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
set_resHeight()
void GU::PixelCoordinate::set_resHeight (const pixels_u newValue)
Definition at line 214 of file PixelCoordinate.cc.
References gu_pixel_coordinate::res_height.
Referenced by CGTEST::TEST_F().
set_resWidth()
void GU::PixelCoordinate::set_resWidth (const pixels_u newValue)
Definition at line 204 of file PixelCoordinate.cc.
References gu_pixel_coordinate::res_width.
Referenced by CGTEST::TEST_F().
set_x()
void GU::PixelCoordinate::set_x (const pixels_t newValue)
Definition at line 184 of file PixelCoordinate.cc.
References gu_pixel_coordinate::x.
Referenced by CGTEST::PixelCoordinateCPPTests::change(), and CGTEST::TEST_F().
set_y()
void GU::PixelCoordinate::set_y (const pixels_t newValue)
Definition at line 194 of file PixelCoordinate.cc.
References gu_pixel_coordinate::y.
Referenced by CGTEST::TEST_F().
x()
pixels_t GU::PixelCoordinate::x () const
Definition at line 179 of file PixelCoordinate.cc.
References gu_pixel_coordinate::x.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
xLowerBound()
pixels_t GU::PixelCoordinate::xLowerBound () const
Definition at line 219 of file PixelCoordinate.cc.
References gu_pixel_coordinate_x_lower_bound().
xUpperBound()
pixels_t GU::PixelCoordinate::xUpperBound () const
Definition at line 224 of file PixelCoordinate.cc.
References gu_pixel_coordinate_x_upper_bound().
y()
pixels_t GU::PixelCoordinate::y () const
Definition at line 189 of file PixelCoordinate.cc.
References gu_pixel_coordinate::y.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
yLowerBound()
pixels_t GU::PixelCoordinate::yLowerBound () const
Definition at line 229 of file PixelCoordinate.cc.
References gu_pixel_coordinate_y_lower_bound().
yUpperBound()
pixels_t GU::PixelCoordinate::yUpperBound () const
Definition at line 234 of file PixelCoordinate.cc.
References gu_pixel_coordinate_y_upper_bound().
The documentation for this struct was generated from the following files:
PixelCoordinate.hpp
PixelCoordinate.cc