gucoordinates: GU::CartesianCoordinate Struct Reference
GU::CartesianCoordinate Struct Reference
#include <CartesianCoordinate.hpp>
Public Member Functions
CartesianCoordinate () NOEXCEPT
CartesianCoordinate (centimetres_t, centimetres_t) NOEXCEPT
CartesianCoordinate (const CartesianCoordinate &other) NOEXCEPT
CartesianCoordinate (const gu_cartesian_coordinate &other) NOEXCEPT
CartesianCoordinate (CartesianCoordinate &&other) NOEXCEPT
CartesianCoordinate (gu_cartesian_coordinate &&other) NOEXCEPT
~CartesianCoordinate () NOEXCEPT
CartesianCoordinate & operator= (const CartesianCoordinate &other) NOEXCEPT
CartesianCoordinate & operator= (const gu_cartesian_coordinate &other) NOEXCEPT
CartesianCoordinate & operator= (CartesianCoordinate &&other) NOEXCEPT
CartesianCoordinate & operator= (gu_cartesian_coordinate &&other) NOEXCEPT
CartesianCoordinate cartesianCoordinateAt (const GU::RelativeCoordinate &) const NOEXCEPT
RelativeCoordinate relativeCoordinateTo (const GU::CartesianCoordinate &) const NOEXCEPT
RelativeCoordinate relativeCoordinateTo (const GU::FieldCoordinate &) const NOEXCEPT
CartesianCoordinate cartesianCoordinateAt (const GU::CameraCoordinate &, const GU::CameraPivot &, const int) const NOEXCEPT
CartesianCoordinate cartesianCoordinateAt (const GU::PixelCoordinate &, const GU::CameraPivot &, const int) const NOEXCEPT
CartesianCoordinate cartesianCoordinateAt (const GU::PercentCoordinate &, const GU::CameraPivot &, const int) const NOEXCEPT
CameraCoordinate cameraCoordinateTo (const GU::CartesianCoordinate &, const GU::CameraPivot &, const int, const pixels_u, const pixels_u) const NOEXCEPT
CameraCoordinate cameraCoordinateTo (const GU::FieldCoordinate &, const GU::CameraPivot &, const int, const pixels_u, const pixels_u) const NOEXCEPT
PixelCoordinate pixelCoordinateTo (const GU::CartesianCoordinate &, const GU::CameraPivot &, const int, const pixels_u, const pixels_u) const NOEXCEPT
PixelCoordinate pixelCoordinateTo (const GU::FieldCoordinate &, const GU::CameraPivot &, const int, const pixels_u, const pixels_u) const NOEXCEPT
PercentCoordinate percentCoordinateTo (const GU::CartesianCoordinate &, const GU::CameraPivot &, const int) const NOEXCEPT
PercentCoordinate percentCoordinateTo (const GU::FieldCoordinate &, const GU::CameraPivot &, const int) const NOEXCEPT
CameraCoordinate clampedCameraCoordinateTo (const GU::CartesianCoordinate &, const GU::CameraPivot &, const int, const pixels_u, const pixels_u) const NOEXCEPT
CameraCoordinate clampedCameraCoordinateTo (const GU::FieldCoordinate &, const GU::CameraPivot &, const int, const pixels_u, const pixels_u) const NOEXCEPT
PixelCoordinate clampedPixelCoordinateTo (const GU::CartesianCoordinate &, const GU::CameraPivot &, const int, const pixels_u, const pixels_u) const NOEXCEPT
PixelCoordinate clampedPixelCoordinateTo (const GU::FieldCoordinate &, const GU::CameraPivot &, const int, const pixels_u, const pixels_u) const NOEXCEPT
PercentCoordinate clampedPercentCoordinateTo (const GU::CartesianCoordinate &, const GU::CameraPivot &, const int) const NOEXCEPT
PercentCoordinate clampedPercentCoordinateTo (const GU::FieldCoordinate &, const GU::CameraPivot &, const int) const NOEXCEPT
centimetres_t x () const NOEXCEPT
void set_x (const centimetres_t) NOEXCEPT
centimetres_t y () const NOEXCEPT
void set_y (const centimetres_t) NOEXCEPT
bool operator== (const CartesianCoordinate &other) const NOEXCEPT
bool operator!= (const CartesianCoordinate &other) const NOEXCEPT
bool operator== (const gu_cartesian_coordinate &other) const NOEXCEPT
bool operator!= (const gu_cartesian_coordinate &other) const NOEXCEPT
Additional Inherited Members
Public Attributes inherited from gu_cartesian_coordinate
millimetres_t x
The x coordinate of the position in centimetres.
millimetres_t y
The y coordinate of the position in centimetres.
Detailed Description
Definition at line 93 of file CartesianCoordinate.hpp.
Constructor & Destructor Documentation
CartesianCoordinate() [1/6]
GU::CartesianCoordinate::CartesianCoordinate ()
Definition at line 66 of file CartesianCoordinate.cc.
CartesianCoordinate() [2/6]
GU::CartesianCoordinate::CartesianCoordinate (centimetres_t t_x, centimetres_t t_y)
Definition at line 68 of file CartesianCoordinate.cc.
CartesianCoordinate() [3/6]
GU::CartesianCoordinate::CartesianCoordinate (const CartesianCoordinate & other)
Definition at line 74 of file CartesianCoordinate.cc.
CartesianCoordinate() [4/6]
GU::CartesianCoordinate::CartesianCoordinate (const gu_cartesian_coordinate & other)
Definition at line 80 of file CartesianCoordinate.cc.
CartesianCoordinate() [5/6]
GU::CartesianCoordinate::CartesianCoordinate (CartesianCoordinate && other)
Definition at line 87 of file CartesianCoordinate.cc.
CartesianCoordinate() [6/6]
GU::CartesianCoordinate::CartesianCoordinate (gu_cartesian_coordinate && other)
Definition at line 93 of file CartesianCoordinate.cc.
~CartesianCoordinate()
GU::CartesianCoordinate::~CartesianCoordinate ()
Definition at line 100 of file CartesianCoordinate.cc.
Member Function Documentation
cameraCoordinateTo() [1/2]
GU::CameraCoordinate GU::CartesianCoordinate::cameraCoordinateTo (const GU::CartesianCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset, const pixels_u resWidth, const pixels_u resHeight) const
Definition at line 176 of file CartesianCoordinate.cc.
cameraCoordinateTo() [2/2]
GU::CameraCoordinate GU::CartesianCoordinate::cameraCoordinateTo (const GU::FieldCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset, const pixels_u resWidth, const pixels_u resHeight) const
Definition at line 181 of file CartesianCoordinate.cc.
cartesianCoordinateAt() [1/4]
GU::CartesianCoordinate GU::CartesianCoordinate::cartesianCoordinateAt (const GU::CameraCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset) const
Definition at line 146 of file CartesianCoordinate.cc.
cartesianCoordinateAt() [2/4]
GU::CartesianCoordinate GU::CartesianCoordinate::cartesianCoordinateAt (const GU::PercentCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset) const
Definition at line 156 of file CartesianCoordinate.cc.
cartesianCoordinateAt() [3/4]
GU::CartesianCoordinate GU::CartesianCoordinate::cartesianCoordinateAt (const GU::PixelCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset) const
Definition at line 151 of file CartesianCoordinate.cc.
cartesianCoordinateAt() [4/4]
GU::CartesianCoordinate GU::CartesianCoordinate::cartesianCoordinateAt (const GU::RelativeCoordinate & target) const
Definition at line 161 of file CartesianCoordinate.cc.
References rr_coord_to_cartesian_coord_from_source().
clampedCameraCoordinateTo() [1/2]
GU::CameraCoordinate GU::CartesianCoordinate::clampedCameraCoordinateTo (const GU::CartesianCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset, const pixels_u resWidth, const pixels_u resHeight) const
Definition at line 206 of file CartesianCoordinate.cc.
clampedCameraCoordinateTo() [2/2]
GU::CameraCoordinate GU::CartesianCoordinate::clampedCameraCoordinateTo (const GU::FieldCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset, const pixels_u resWidth, const pixels_u resHeight) const
Definition at line 211 of file CartesianCoordinate.cc.
clampedPercentCoordinateTo() [1/2]
GU::PercentCoordinate GU::CartesianCoordinate::clampedPercentCoordinateTo (const GU::CartesianCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset) const
Definition at line 226 of file CartesianCoordinate.cc.
clampedPercentCoordinateTo() [2/2]
GU::PercentCoordinate GU::CartesianCoordinate::clampedPercentCoordinateTo (const GU::FieldCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset) const
Definition at line 231 of file CartesianCoordinate.cc.
clampedPixelCoordinateTo() [1/2]
GU::PixelCoordinate GU::CartesianCoordinate::clampedPixelCoordinateTo (const GU::CartesianCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset, const pixels_u resWidth, const pixels_u resHeight) const
Definition at line 216 of file CartesianCoordinate.cc.
clampedPixelCoordinateTo() [2/2]
GU::PixelCoordinate GU::CartesianCoordinate::clampedPixelCoordinateTo (const GU::FieldCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset, const pixels_u resWidth, const pixels_u resHeight) const
Definition at line 221 of file CartesianCoordinate.cc.
operator!=() [1/2]
bool GU::CartesianCoordinate::operator!= (const CartesianCoordinate & other) const
Definition at line 261 of file CartesianCoordinate.cc.
operator!=() [2/2]
bool GU::CartesianCoordinate::operator!= (const gu_cartesian_coordinate & other) const
Definition at line 271 of file CartesianCoordinate.cc.
operator=() [1/4]
GU::CartesianCoordinate & GU::CartesianCoordinate::operator= (CartesianCoordinate && other)
Definition at line 125 of file CartesianCoordinate.cc.
operator=() [2/4]
GU::CartesianCoordinate & GU::CartesianCoordinate::operator= (const CartesianCoordinate & other)
Definition at line 102 of file CartesianCoordinate.cc.
operator=() [3/4]
GU::CartesianCoordinate & GU::CartesianCoordinate::operator= (const gu_cartesian_coordinate & other)
Definition at line 113 of file CartesianCoordinate.cc.
operator=() [4/4]
GU::CartesianCoordinate & GU::CartesianCoordinate::operator= (gu_cartesian_coordinate && other)
Definition at line 135 of file CartesianCoordinate.cc.
operator==() [1/2]
bool GU::CartesianCoordinate::operator== (const CartesianCoordinate & other) const
Definition at line 256 of file CartesianCoordinate.cc.
References gu_cartesian_coordinate_equals().
operator==() [2/2]
bool GU::CartesianCoordinate::operator== (const gu_cartesian_coordinate & other) const
Definition at line 266 of file CartesianCoordinate.cc.
References gu_cartesian_coordinate_equals().
percentCoordinateTo() [1/2]
GU::PercentCoordinate GU::CartesianCoordinate::percentCoordinateTo (const GU::CartesianCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset) const
Definition at line 196 of file CartesianCoordinate.cc.
percentCoordinateTo() [2/2]
GU::PercentCoordinate GU::CartesianCoordinate::percentCoordinateTo (const GU::FieldCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset) const
Definition at line 201 of file CartesianCoordinate.cc.
pixelCoordinateTo() [1/2]
GU::PixelCoordinate GU::CartesianCoordinate::pixelCoordinateTo (const GU::CartesianCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset, const pixels_u resWidth, const pixels_u resHeight) const
Definition at line 186 of file CartesianCoordinate.cc.
pixelCoordinateTo() [2/2]
GU::PixelCoordinate GU::CartesianCoordinate::pixelCoordinateTo (const GU::FieldCoordinate & target, const GU::CameraPivot & cameraPivot, const int cameraOffset, const pixels_u resWidth, const pixels_u resHeight) const
Definition at line 191 of file CartesianCoordinate.cc.
relativeCoordinateTo() [1/2]
GU::RelativeCoordinate GU::CartesianCoordinate::relativeCoordinateTo (const GU::CartesianCoordinate & target) const
Definition at line 166 of file CartesianCoordinate.cc.
References cartesian_coord_to_rr_coord_from_source().
relativeCoordinateTo() [2/2]
GU::RelativeCoordinate GU::CartesianCoordinate::relativeCoordinateTo (const GU::FieldCoordinate & target) const
Definition at line 171 of file CartesianCoordinate.cc.
set_x()
void GU::CartesianCoordinate::set_x (const centimetres_t newValue)
Definition at line 241 of file CartesianCoordinate.cc.
References gu_cartesian_coordinate::x.
Referenced by CGTEST::CartesianCoordinateCPPTests::change(), and CGTEST::TEST_F().
set_y()
void GU::CartesianCoordinate::set_y (const centimetres_t newValue)
Definition at line 251 of file CartesianCoordinate.cc.
References gu_cartesian_coordinate::y.
Referenced by CGTEST::TEST_F().
x()
centimetres_t GU::CartesianCoordinate::x () const
Definition at line 236 of file CartesianCoordinate.cc.
References gu_cartesian_coordinate::x.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
y()
centimetres_t GU::CartesianCoordinate::y () const
Definition at line 246 of file CartesianCoordinate.cc.
References gu_cartesian_coordinate::y.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
The documentation for this struct was generated from the following files:
CartesianCoordinate.hpp
CartesianCoordinate.cc