gucoordinates: GU::Camera Struct Reference
GU::Camera Struct Reference
#include <Camera.hpp>
Public Member Functions
Camera () NOEXCEPT
Camera (centimetres_d, centimetres_d, degrees_d, degrees_d, degrees_d) NOEXCEPT
Camera (const Camera &other) NOEXCEPT
Camera (const gu_camera &other) NOEXCEPT
Camera (Camera &&other) NOEXCEPT
Camera (gu_camera &&other) NOEXCEPT
~Camera () NOEXCEPT
Camera & operator= (const Camera &other) NOEXCEPT
Camera & operator= (const gu_camera &other) NOEXCEPT
Camera & operator= (Camera &&other) NOEXCEPT
Camera & operator= (gu_camera &&other) NOEXCEPT
centimetres_d height () const NOEXCEPT
void set_height (const centimetres_d) NOEXCEPT
centimetres_d centerOffset () const NOEXCEPT
void set_centerOffset (const centimetres_d) NOEXCEPT
degrees_d vDirection () const NOEXCEPT
void set_vDirection (const degrees_d) NOEXCEPT
degrees_d vFov () const NOEXCEPT
void set_vFov (const degrees_d) NOEXCEPT
degrees_d hFov () const NOEXCEPT
void set_hFov (const degrees_d) NOEXCEPT
bool operator== (const Camera &other) const NOEXCEPT
bool operator!= (const Camera &other) const NOEXCEPT
bool operator== (const gu_camera &other) const NOEXCEPT
bool operator!= (const gu_camera &other) const NOEXCEPT
Additional Inherited Members
Public Attributes inherited from gu_camera
centimetres_d height
The height from the pivot of the camera to the middle of the camera.
centimetres_d centerOffset
The distance the camera is from the center point.
degrees_d vDirection
The degree in which the camera is facing in the vertical direction.
degrees_d vFov
The vertical field of view.
degrees_d hFov
The horizontal field of view.
Detailed Description
Definition at line 68 of file Camera.hpp.
Constructor & Destructor Documentation
Camera() [1/6]
GU::Camera::Camera ()
Definition at line 61 of file CameraCPP.cc.
Camera() [2/6]
GU::Camera::Camera (centimetres_d t_height, centimetres_d t_centerOffset, degrees_d t_vDirection, degrees_d t_vFov, degrees_d t_hFov)
Definition at line 63 of file CameraCPP.cc.
Camera() [3/6]
GU::Camera::Camera (const Camera & other)
Definition at line 72 of file CameraCPP.cc.
Camera() [4/6]
GU::Camera::Camera (const gu_camera & other)
Definition at line 81 of file CameraCPP.cc.
Camera() [5/6]
GU::Camera::Camera (Camera && other)
Definition at line 91 of file CameraCPP.cc.
Camera() [6/6]
GU::Camera::Camera (gu_camera && other)
Definition at line 100 of file CameraCPP.cc.
~Camera()
GU::Camera::~Camera ()
Definition at line 110 of file CameraCPP.cc.
Member Function Documentation
centerOffset()
centimetres_d GU::Camera::centerOffset () const
Definition at line 178 of file CameraCPP.cc.
References gu_camera::centerOffset.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
height()
centimetres_d GU::Camera::height () const
Definition at line 168 of file CameraCPP.cc.
References gu_camera::height.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
hFov()
degrees_d GU::Camera::hFov () const
Definition at line 208 of file CameraCPP.cc.
References gu_camera::hFov.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
operator!=() [1/2]
bool GU::Camera::operator!= (const Camera & other) const
Definition at line 223 of file CameraCPP.cc.
operator!=() [2/2]
bool GU::Camera::operator!= (const gu_camera & other) const
Definition at line 233 of file CameraCPP.cc.
operator=() [1/4]
GU::Camera & GU::Camera::operator= (Camera && other)
Definition at line 141 of file CameraCPP.cc.
operator=() [2/4]
GU::Camera & GU::Camera::operator= (const Camera & other)
Definition at line 112 of file CameraCPP.cc.
operator=() [3/4]
GU::Camera & GU::Camera::operator= (const gu_camera & other)
Definition at line 126 of file CameraCPP.cc.
operator=() [4/4]
GU::Camera & GU::Camera::operator= (gu_camera && other)
Definition at line 154 of file CameraCPP.cc.
operator==() [1/2]
bool GU::Camera::operator== (const Camera & other) const
Definition at line 218 of file CameraCPP.cc.
References gu_camera_equals().
operator==() [2/2]
bool GU::Camera::operator== (const gu_camera & other) const
Definition at line 228 of file CameraCPP.cc.
References gu_camera_equals().
set_centerOffset()
void GU::Camera::set_centerOffset (const centimetres_d newValue)
Definition at line 183 of file CameraCPP.cc.
References gu_camera::centerOffset.
Referenced by CGTEST::TEST_F().
set_height()
void GU::Camera::set_height (const centimetres_d newValue)
Definition at line 173 of file CameraCPP.cc.
References gu_camera::height.
Referenced by CGTEST::CameraCPPTests::change(), and CGTEST::TEST_F().
set_hFov()
void GU::Camera::set_hFov (const degrees_d newValue)
Definition at line 213 of file CameraCPP.cc.
References gu_camera::hFov.
Referenced by CGTEST::TEST_F().
set_vDirection()
void GU::Camera::set_vDirection (const degrees_d newValue)
Definition at line 193 of file CameraCPP.cc.
References gu_camera::vDirection.
Referenced by CGTEST::TEST_F().
set_vFov()
void GU::Camera::set_vFov (const degrees_d newValue)
Definition at line 203 of file CameraCPP.cc.
References gu_camera::vFov.
Referenced by CGTEST::TEST_F().
vDirection()
degrees_d GU::Camera::vDirection () const
Definition at line 188 of file CameraCPP.cc.
References gu_camera::vDirection.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
vFov()
degrees_d GU::Camera::vFov () const
Definition at line 198 of file CameraCPP.cc.
References gu_camera::vFov.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
The documentation for this struct was generated from the following files:
Camera.hpp
CameraCPP.cc