gucoordinates: GU::RelativeCoordinate Struct Reference
GU::RelativeCoordinate Struct Reference
#include <RelativeCoordinate.hpp>
Public Member Functions
RelativeCoordinate () NOEXCEPT
RelativeCoordinate (degrees_d, millimetres_u) NOEXCEPT
RelativeCoordinate (const RelativeCoordinate &other) NOEXCEPT
RelativeCoordinate (const gu_relative_coordinate &other) NOEXCEPT
RelativeCoordinate (RelativeCoordinate &&other) NOEXCEPT
RelativeCoordinate (gu_relative_coordinate &&other) NOEXCEPT
~RelativeCoordinate () NOEXCEPT
RelativeCoordinate & operator= (const RelativeCoordinate &other) NOEXCEPT
RelativeCoordinate & operator= (const gu_relative_coordinate &other) NOEXCEPT
RelativeCoordinate & operator= (RelativeCoordinate &&other) NOEXCEPT
RelativeCoordinate & operator= (gu_relative_coordinate &&other) NOEXCEPT
CameraCoordinate cameraCoordinate (const GU::CameraPivot &, const int, const pixels_u, const pixels_u) const NOEXCEPT
PixelCoordinate pixelCoordinate (const GU::CameraPivot &, const int, const pixels_u, const pixels_u) const NOEXCEPT
PercentCoordinate percentCoordinate (const GU::CameraPivot &, const int) const NOEXCEPT
CameraCoordinate clampedCameraCoordinate (const GU::CameraPivot &, const int, const pixels_u, const pixels_u) const NOEXCEPT
PixelCoordinate clampedPixelCoordinate (const GU::CameraPivot &, const int, const pixels_u, const pixels_u) const NOEXCEPT
PercentCoordinate clampedPercentCoordinate (const GU::CameraPivot &, const int) const NOEXCEPT
RelativeCoordinate relativeCoordinateTo (const RelativeCoordinate &) const NOEXCEPT
CartesianCoordinate cartesianCoordinate () const NOEXCEPT
FieldCoordinate fieldCoordinate (const degrees_t) const NOEXCEPT
degrees_d direction () const NOEXCEPT
void set_direction (const degrees_d) NOEXCEPT
millimetres_u distance () const NOEXCEPT
void set_distance (const millimetres_u) NOEXCEPT
bool operator== (const RelativeCoordinate &other) const NOEXCEPT
bool operator!= (const RelativeCoordinate &other) const NOEXCEPT
bool operator== (const gu_relative_coordinate &other) const NOEXCEPT
bool operator!= (const gu_relative_coordinate &other) const NOEXCEPT
Additional Inherited Members
Public Attributes inherited from gu_relative_coordinate
degrees_d direction
The heading towards the coordinate.
millimetres_u distance
The distance to the coordinate.
Detailed Description
Definition at line 91 of file RelativeCoordinate.hpp.
Constructor & Destructor Documentation
RelativeCoordinate() [1/6]
GU::RelativeCoordinate::RelativeCoordinate ()
Definition at line 66 of file RelativeCoordinate.cc.
RelativeCoordinate() [2/6]
GU::RelativeCoordinate::RelativeCoordinate (degrees_d t_direction, millimetres_u t_distance)
Definition at line 68 of file RelativeCoordinate.cc.
RelativeCoordinate() [3/6]
GU::RelativeCoordinate::RelativeCoordinate (const RelativeCoordinate & other)
Definition at line 74 of file RelativeCoordinate.cc.
RelativeCoordinate() [4/6]
GU::RelativeCoordinate::RelativeCoordinate (const gu_relative_coordinate & other)
Definition at line 80 of file RelativeCoordinate.cc.
RelativeCoordinate() [5/6]
GU::RelativeCoordinate::RelativeCoordinate (RelativeCoordinate && other)
Definition at line 87 of file RelativeCoordinate.cc.
RelativeCoordinate() [6/6]
GU::RelativeCoordinate::RelativeCoordinate (gu_relative_coordinate && other)
Definition at line 93 of file RelativeCoordinate.cc.
~RelativeCoordinate()
GU::RelativeCoordinate::~RelativeCoordinate ()
Definition at line 100 of file RelativeCoordinate.cc.
Member Function Documentation
cameraCoordinate()
GU::CameraCoordinate GU::RelativeCoordinate::cameraCoordinate (const GU::CameraPivot & cameraPivot, const int cameraOffset, const pixels_u resWidth, const pixels_u resHeight) const
Definition at line 146 of file RelativeCoordinate.cc.
cartesianCoordinate()
GU::CartesianCoordinate GU::RelativeCoordinate::cartesianCoordinate () const
Definition at line 181 of file RelativeCoordinate.cc.
References rr_coord_to_cartesian_coord().
clampedCameraCoordinate()
GU::CameraCoordinate GU::RelativeCoordinate::clampedCameraCoordinate (const GU::CameraPivot & cameraPivot, const int cameraOffset, const pixels_u resWidth, const pixels_u resHeight) const
Definition at line 161 of file RelativeCoordinate.cc.
clampedPercentCoordinate()
GU::PercentCoordinate GU::RelativeCoordinate::clampedPercentCoordinate (const GU::CameraPivot & cameraPivot, const int cameraOffset) const
Definition at line 171 of file RelativeCoordinate.cc.
References clamped_rr_coord_to_pct_coord().
clampedPixelCoordinate()
GU::PixelCoordinate GU::RelativeCoordinate::clampedPixelCoordinate (const GU::CameraPivot & cameraPivot, const int cameraOffset, const pixels_u resWidth, const pixels_u resHeight) const
Definition at line 166 of file RelativeCoordinate.cc.
direction()
degrees_d GU::RelativeCoordinate::direction () const
Definition at line 191 of file RelativeCoordinate.cc.
References gu_relative_coordinate::direction.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
distance()
millimetres_u GU::RelativeCoordinate::distance () const
Definition at line 201 of file RelativeCoordinate.cc.
References gu_relative_coordinate::distance.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
fieldCoordinate()
GU::FieldCoordinate GU::RelativeCoordinate::fieldCoordinate (const degrees_t heading) const
Definition at line 186 of file RelativeCoordinate.cc.
References rr_coord_to_field_coord().
operator!=() [1/2]
bool GU::RelativeCoordinate::operator!= (const gu_relative_coordinate & other) const
Definition at line 226 of file RelativeCoordinate.cc.
operator!=() [2/2]
bool GU::RelativeCoordinate::operator!= (const RelativeCoordinate & other) const
Definition at line 216 of file RelativeCoordinate.cc.
operator=() [1/4]
GU::RelativeCoordinate & GU::RelativeCoordinate::operator= (const gu_relative_coordinate & other)
Definition at line 113 of file RelativeCoordinate.cc.
operator=() [2/4]
GU::RelativeCoordinate & GU::RelativeCoordinate::operator= (const RelativeCoordinate & other)
Definition at line 102 of file RelativeCoordinate.cc.
operator=() [3/4]
GU::RelativeCoordinate & GU::RelativeCoordinate::operator= (gu_relative_coordinate && other)
Definition at line 135 of file RelativeCoordinate.cc.
operator=() [4/4]
GU::RelativeCoordinate & GU::RelativeCoordinate::operator= (RelativeCoordinate && other)
Definition at line 125 of file RelativeCoordinate.cc.
operator==() [1/2]
bool GU::RelativeCoordinate::operator== (const gu_relative_coordinate & other) const
Definition at line 221 of file RelativeCoordinate.cc.
References gu_relative_coordinate_equals().
operator==() [2/2]
bool GU::RelativeCoordinate::operator== (const RelativeCoordinate & other) const
Definition at line 211 of file RelativeCoordinate.cc.
References gu_relative_coordinate_equals().
percentCoordinate()
GU::PercentCoordinate GU::RelativeCoordinate::percentCoordinate (const GU::CameraPivot & cameraPivot, const int cameraOffset) const
Definition at line 156 of file RelativeCoordinate.cc.
References rr_coord_to_pct_coord().
pixelCoordinate()
GU::PixelCoordinate GU::RelativeCoordinate::pixelCoordinate (const GU::CameraPivot & cameraPivot, const int cameraOffset, const pixels_u resWidth, const pixels_u resHeight) const
Definition at line 151 of file RelativeCoordinate.cc.
relativeCoordinateTo()
GU::RelativeCoordinate GU::RelativeCoordinate::relativeCoordinateTo (const RelativeCoordinate & coord) const
Definition at line 176 of file RelativeCoordinate.cc.
References relativeCoordinateTo().
Referenced by relativeCoordinateTo().
set_direction()
void GU::RelativeCoordinate::set_direction (const degrees_d newValue)
Definition at line 196 of file RelativeCoordinate.cc.
References gu_relative_coordinate::direction.
Referenced by CGTEST::RelativeCoordinateCPPTests::change(), and CGTEST::TEST_F().
set_distance()
void GU::RelativeCoordinate::set_distance (const millimetres_u newValue)
Definition at line 206 of file RelativeCoordinate.cc.
References gu_relative_coordinate::distance.
Referenced by CGTEST::TEST_F().
The documentation for this struct was generated from the following files:
RelativeCoordinate.hpp
RelativeCoordinate.cc