gucoordinates: GU::CameraPivot Struct Reference
GU::CameraPivot Struct Reference
#include <CameraPivot.hpp>
Public Member Functions
CameraPivot () NOEXCEPT
CameraPivot (const degrees_d, const degrees_d, const centimetres_d, const gu_camera[2], int) NOEXCEPT
CameraPivot (const CameraPivot &other) NOEXCEPT
CameraPivot (const gu_camera_pivot &other) NOEXCEPT
CameraPivot (CameraPivot &&other) NOEXCEPT
CameraPivot (gu_camera_pivot &&other) NOEXCEPT
~CameraPivot () NOEXCEPT
CameraPivot & operator= (const CameraPivot &other) NOEXCEPT
CameraPivot & operator= (const gu_camera_pivot &other) NOEXCEPT
CameraPivot & operator= (CameraPivot &&other) NOEXCEPT
CameraPivot & operator= (gu_camera_pivot &&other) NOEXCEPT
degrees_d pitch () const NOEXCEPT
void set_pitch (const degrees_d) NOEXCEPT
degrees_d yaw () const NOEXCEPT
void set_yaw (const degrees_d) NOEXCEPT
centimetres_d height () const NOEXCEPT
void set_height (const centimetres_d) NOEXCEPT
const gu_camera * cameras () const NOEXCEPT
void set_cameras (const gu_camera[2]) NOEXCEPT
Camera camera (const int) const NOEXCEPT
void set_camera (const int, const Camera) NOEXCEPT
int numCameras () const NOEXCEPT
void set_numCameras (const int) NOEXCEPT
bool operator== (const CameraPivot &other) const NOEXCEPT
bool operator!= (const CameraPivot &other) const NOEXCEPT
bool operator== (const gu_camera_pivot &other) const NOEXCEPT
bool operator!= (const gu_camera_pivot &other) const NOEXCEPT
Additional Inherited Members
Public Attributes inherited from gu_camera_pivot
degrees_d pitch
The vertical orientation of the pivot point.
degrees_d yaw
The horizontal orientation of the pivot point.
centimetres_d height
The vertical distance from the ground to the pivot point.
gu_camera cameras [2]
The gu_cameras attached to this pivot point.
int numCameras
The number of elements in cameras.
Detailed Description
Definition at line 70 of file CameraPivot.hpp.
Constructor & Destructor Documentation
CameraPivot() [1/6]
GU::CameraPivot::CameraPivot ()
Definition at line 64 of file CameraPivot.cc.
CameraPivot() [2/6]
GU::CameraPivot::CameraPivot (const degrees_d t_pitch, const degrees_d t_yaw, const centimetres_d t_height, const gu_camera t_cameras[2], int t_numCameras)
Definition at line 66 of file CameraPivot.cc.
CameraPivot() [3/6]
GU::CameraPivot::CameraPivot (const CameraPivot & other)
Definition at line 75 of file CameraPivot.cc.
CameraPivot() [4/6]
GU::CameraPivot::CameraPivot (const gu_camera_pivot & other)
Definition at line 84 of file CameraPivot.cc.
CameraPivot() [5/6]
GU::CameraPivot::CameraPivot (CameraPivot && other)
Definition at line 94 of file CameraPivot.cc.
CameraPivot() [6/6]
GU::CameraPivot::CameraPivot (gu_camera_pivot && other)
Definition at line 103 of file CameraPivot.cc.
~CameraPivot()
GU::CameraPivot::~CameraPivot ()
Definition at line 113 of file CameraPivot.cc.
Member Function Documentation
camera()
GU::Camera GU::CameraPivot::camera (const int index) const
Definition at line 212 of file CameraPivot.cc.
References gu_camera_pivot::cameras.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
cameras()
const gu_camera * GU::CameraPivot::cameras () const
Definition at line 202 of file CameraPivot.cc.
References gu_camera_pivot::cameras.
height()
centimetres_d GU::CameraPivot::height () const
Definition at line 192 of file CameraPivot.cc.
References gu_camera_pivot::height.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
numCameras()
int GU::CameraPivot::numCameras () const
Definition at line 222 of file CameraPivot.cc.
References gu_camera_pivot::numCameras.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), and CGTEST::GUCoordinatesTests< Class >::nequals().
operator!=() [1/2]
bool GU::CameraPivot::operator!= (const CameraPivot & other) const
Definition at line 237 of file CameraPivot.cc.
operator!=() [2/2]
bool GU::CameraPivot::operator!= (const gu_camera_pivot & other) const
Definition at line 247 of file CameraPivot.cc.
operator=() [1/4]
GU::CameraPivot & GU::CameraPivot::operator= (CameraPivot && other)
Definition at line 144 of file CameraPivot.cc.
operator=() [2/4]
GU::CameraPivot & GU::CameraPivot::operator= (const CameraPivot & other)
Definition at line 115 of file CameraPivot.cc.
operator=() [3/4]
GU::CameraPivot & GU::CameraPivot::operator= (const gu_camera_pivot & other)
Definition at line 129 of file CameraPivot.cc.
operator=() [4/4]
GU::CameraPivot & GU::CameraPivot::operator= (gu_camera_pivot && other)
Definition at line 157 of file CameraPivot.cc.
operator==() [1/2]
bool GU::CameraPivot::operator== (const CameraPivot & other) const
Definition at line 232 of file CameraPivot.cc.
References gu_camera_pivot_equals().
operator==() [2/2]
bool GU::CameraPivot::operator== (const gu_camera_pivot & other) const
Definition at line 242 of file CameraPivot.cc.
References gu_camera_pivot_equals().
pitch()
degrees_d GU::CameraPivot::pitch () const
Definition at line 171 of file CameraPivot.cc.
References gu_camera_pivot::pitch.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
set_camera()
void GU::CameraPivot::set_camera (const int index, const Camera)
Definition at line 217 of file CameraPivot.cc.
References gu_camera_pivot::cameras.
Referenced by CGTEST::TEST_F().
set_cameras()
void GU::CameraPivot::set_cameras (const gu_camera newValue[2])
Definition at line 207 of file CameraPivot.cc.
References gu_camera_pivot::cameras, and GU_CAMERA_PIVOT_NUM_CAMERAS.
set_height()
void GU::CameraPivot::set_height (const centimetres_d newValue)
Definition at line 197 of file CameraPivot.cc.
References gu_camera_pivot::height.
Referenced by CGTEST::TEST_F().
set_numCameras()
void GU::CameraPivot::set_numCameras (const int newValue)
Definition at line 227 of file CameraPivot.cc.
References gu_camera_pivot::numCameras.
set_pitch()
void GU::CameraPivot::set_pitch (const degrees_d newValue)
Definition at line 176 of file CameraPivot.cc.
References gu_camera_pivot::pitch.
Referenced by CGTEST::CameraPivotCPPTests::change(), and CGTEST::TEST_F().
set_yaw()
void GU::CameraPivot::set_yaw (const degrees_d newValue)
Definition at line 186 of file CameraPivot.cc.
References gu_camera_pivot::yaw.
Referenced by CGTEST::TEST_F().
yaw()
degrees_d GU::CameraPivot::yaw () const
Definition at line 181 of file CameraPivot.cc.
References gu_camera_pivot::yaw.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
The documentation for this struct was generated from the following files:
CameraPivot.hpp
CameraPivot.cc