gucoordinates: GU::CameraCoordinate Struct Reference
GU::CameraCoordinate Struct Reference
#include <CameraCoordinate.hpp>
Public Member Functions
CameraCoordinate () NOEXCEPT
CameraCoordinate (pixels_u, pixels_u, pixels_u, pixels_u) NOEXCEPT
CameraCoordinate (const CameraCoordinate &other) NOEXCEPT
CameraCoordinate (const gu_camera_coordinate &other) NOEXCEPT
CameraCoordinate (CameraCoordinate &&other) NOEXCEPT
CameraCoordinate (gu_camera_coordinate &&other) NOEXCEPT
~CameraCoordinate () NOEXCEPT
CameraCoordinate & operator= (const CameraCoordinate &other) NOEXCEPT
CameraCoordinate & operator= (const gu_camera_coordinate &other) NOEXCEPT
CameraCoordinate & operator= (CameraCoordinate &&other) NOEXCEPT
CameraCoordinate & operator= (gu_camera_coordinate &&other) NOEXCEPT
GU::PixelCoordinate pixelCoordinate () const NOEXCEPT
GU::PercentCoordinate percentCoordinate () const NOEXCEPT
RelativeCoordinate relativeCoordinate (const GU::CameraPivot &, const int) const NOEXCEPT
pixels_u x () const NOEXCEPT
void set_x (const pixels_u) NOEXCEPT
pixels_u y () const NOEXCEPT
void set_y (const pixels_u) NOEXCEPT
pixels_u resWidth () const NOEXCEPT
void set_resWidth (const pixels_u) NOEXCEPT
pixels_u resHeight () const NOEXCEPT
void set_resHeight (const pixels_u) NOEXCEPT
pixels_t xLowerBound () const NOEXCEPT
pixels_t xUpperBound () const NOEXCEPT
pixels_t yLowerBound () const NOEXCEPT
pixels_t yUpperBound () const NOEXCEPT
bool operator== (const CameraCoordinate &other) const NOEXCEPT
bool operator!= (const CameraCoordinate &other) const NOEXCEPT
bool operator== (const gu_camera_coordinate &other) const NOEXCEPT
bool operator!= (const gu_camera_coordinate &other) const NOEXCEPT
Additional Inherited Members
Public Attributes inherited from gu_camera_coordinate
pixels_u x
The x coordinate of the pixel within the image.
pixels_u y
The y coordinate of the pixel within the image.
pixels_u res_width
The width of the resolution of the image.
pixels_u res_height
The height of the resolution of the image.
Detailed Description
Definition at line 86 of file CameraCoordinate.hpp.
Constructor & Destructor Documentation
CameraCoordinate() [1/6]
GU::CameraCoordinate::CameraCoordinate ()
Definition at line 66 of file CameraCoordinate.cc.
CameraCoordinate() [2/6]
GU::CameraCoordinate::CameraCoordinate (pixels_u t_x, pixels_u t_y, pixels_u t_resWidth, pixels_u t_resHeight)
Definition at line 68 of file CameraCoordinate.cc.
CameraCoordinate() [3/6]
GU::CameraCoordinate::CameraCoordinate (const CameraCoordinate & other)
Definition at line 76 of file CameraCoordinate.cc.
CameraCoordinate() [4/6]
GU::CameraCoordinate::CameraCoordinate (const gu_camera_coordinate & other)
Definition at line 84 of file CameraCoordinate.cc.
CameraCoordinate() [5/6]
GU::CameraCoordinate::CameraCoordinate (CameraCoordinate && other)
Definition at line 93 of file CameraCoordinate.cc.
CameraCoordinate() [6/6]
GU::CameraCoordinate::CameraCoordinate (gu_camera_coordinate && other)
Definition at line 101 of file CameraCoordinate.cc.
~CameraCoordinate()
GU::CameraCoordinate::~CameraCoordinate ()
Definition at line 110 of file CameraCoordinate.cc.
Member Function Documentation
operator!=() [1/2]
bool GU::CameraCoordinate::operator!= (const CameraCoordinate & other) const
Definition at line 244 of file CameraCoordinate.cc.
operator!=() [2/2]
bool GU::CameraCoordinate::operator!= (const gu_camera_coordinate & other) const
Definition at line 254 of file CameraCoordinate.cc.
operator=() [1/4]
GU::CameraCoordinate & GU::CameraCoordinate::operator= (CameraCoordinate && other)
Definition at line 139 of file CameraCoordinate.cc.
operator=() [2/4]
GU::CameraCoordinate & GU::CameraCoordinate::operator= (const CameraCoordinate & other)
Definition at line 112 of file CameraCoordinate.cc.
operator=() [3/4]
GU::CameraCoordinate & GU::CameraCoordinate::operator= (const gu_camera_coordinate & other)
Definition at line 125 of file CameraCoordinate.cc.
operator=() [4/4]
GU::CameraCoordinate & GU::CameraCoordinate::operator= (gu_camera_coordinate && other)
Definition at line 151 of file CameraCoordinate.cc.
operator==() [1/2]
bool GU::CameraCoordinate::operator== (const CameraCoordinate & other) const
Definition at line 239 of file CameraCoordinate.cc.
References gu_camera_coordinate_equals().
operator==() [2/2]
bool GU::CameraCoordinate::operator== (const gu_camera_coordinate & other) const
Definition at line 249 of file CameraCoordinate.cc.
References gu_camera_coordinate_equals().
percentCoordinate()
GU::PercentCoordinate GU::CameraCoordinate::percentCoordinate () const
Definition at line 169 of file CameraCoordinate.cc.
pixelCoordinate()
GU::PixelCoordinate GU::CameraCoordinate::pixelCoordinate () const
Definition at line 164 of file CameraCoordinate.cc.
References cam_coord_to_px_coord().
relativeCoordinate()
GU::RelativeCoordinate GU::CameraCoordinate::relativeCoordinate (const GU::CameraPivot & cameraPivot, const int cameraOffset) const
Definition at line 174 of file CameraCoordinate.cc.
resHeight()
pixels_u GU::CameraCoordinate::resHeight () const
Definition at line 209 of file CameraCoordinate.cc.
References gu_camera_coordinate::res_height.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
resWidth()
pixels_u GU::CameraCoordinate::resWidth () const
Definition at line 199 of file CameraCoordinate.cc.
References gu_camera_coordinate::res_width.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
set_resHeight()
void GU::CameraCoordinate::set_resHeight (const pixels_u newValue)
Definition at line 214 of file CameraCoordinate.cc.
References gu_camera_coordinate::res_height.
Referenced by CGTEST::TEST_F().
set_resWidth()
void GU::CameraCoordinate::set_resWidth (const pixels_u newValue)
Definition at line 204 of file CameraCoordinate.cc.
References gu_camera_coordinate::res_width.
Referenced by CGTEST::TEST_F().
set_x()
void GU::CameraCoordinate::set_x (const pixels_u newValue)
Definition at line 184 of file CameraCoordinate.cc.
References gu_camera_coordinate::x.
Referenced by CGTEST::CameraCoordinateCPPTests::change(), and CGTEST::TEST_F().
set_y()
void GU::CameraCoordinate::set_y (const pixels_u newValue)
Definition at line 194 of file CameraCoordinate.cc.
References gu_camera_coordinate::y.
Referenced by CGTEST::TEST_F().
x()
pixels_u GU::CameraCoordinate::x () const
Definition at line 179 of file CameraCoordinate.cc.
References gu_camera_coordinate::x.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
xLowerBound()
pixels_t GU::CameraCoordinate::xLowerBound () const
Definition at line 219 of file CameraCoordinate.cc.
References gu_camera_coordinate_x_lower_bound().
xUpperBound()
pixels_t GU::CameraCoordinate::xUpperBound () const
Definition at line 224 of file CameraCoordinate.cc.
References gu_camera_coordinate_x_upper_bound().
y()
pixels_u GU::CameraCoordinate::y () const
Definition at line 189 of file CameraCoordinate.cc.
References gu_camera_coordinate::y.
Referenced by CGTEST::GUCoordinatesTests< Class >::equals(), CGTEST::GUCoordinatesTests< Class >::nequals(), and CGTEST::TEST_F().
yLowerBound()
pixels_t GU::CameraCoordinate::yLowerBound () const
Definition at line 229 of file CameraCoordinate.cc.
References gu_camera_coordinate_y_lower_bound().
yUpperBound()
pixels_t GU::CameraCoordinate::yUpperBound () const
Definition at line 234 of file CameraCoordinate.cc.
References gu_camera_coordinate_y_upper_bound().
The documentation for this struct was generated from the following files:
CameraCoordinate.hpp
CameraCoordinate.cc