gucoordinates: GU::OptionalCoordinate< Raw, Wrapped > Struct Template Reference
GU::OptionalCoordinate< Raw, Wrapped > Struct Template Reference
#include <OptionalCoordinate.hpp>
Public Member Functions
OptionalCoordinate () NOEXCEPT
OptionalCoordinate (const Wrapped t_value) NOEXCEPT
OptionalCoordinate (const bool t_has_value, const Wrapped t_value) NOEXCEPT
OptionalCoordinate (const OptionalCoordinate< Raw, Wrapped > &other) NOEXCEPT
OptionalCoordinate (const Raw &other) NOEXCEPT
OptionalCoordinate (const std::optional< Wrapped > &other) NOEXCEPT
OptionalCoordinate (OptionalCoordinate< Raw, Wrapped > &&other) NOEXCEPT
~OptionalCoordinate () NOEXCEPT
OptionalCoordinate< Raw, Wrapped > & operator= (const OptionalCoordinate< Raw, Wrapped > &other) NOEXCEPT
OptionalCoordinate< Raw, Wrapped > & operator= (const Raw &other) NOEXCEPT
OptionalCoordinate< Raw, Wrapped > & operator= (const std::optional< Wrapped > &other) NOEXCEPT
OptionalCoordinate< Raw, Wrapped > & operator= (OptionalCoordinate< Raw, Wrapped > &&other) NOEXCEPT
bool has_value () const NOEXCEPT
void set_has_value (const bool newValue) NOEXCEPT
Wrapped value () const NOEXCEPT
void set_value (const Wrapped newValue) NOEXCEPT
std::optional< Wrapped > asOptional () const NOEXCEPT
Detailed Description
template<class Raw, class Wrapped>
struct GU::OptionalCoordinate< Raw, Wrapped >
Definition at line 69 of file OptionalCoordinate.hpp.
Constructor & Destructor Documentation
OptionalCoordinate() [1/7]
template<class Raw , class Wrapped > GU::OptionalCoordinate< Raw, Wrapped >::OptionalCoordinate () inline
Definition at line 71 of file OptionalCoordinate.hpp.
OptionalCoordinate() [2/7]
template<class Raw , class Wrapped > GU::OptionalCoordinate< Raw, Wrapped >::OptionalCoordinate (const Wrapped t_value) inline
Definition at line 73 of file OptionalCoordinate.hpp.
References GU::OptionalCoordinate< Raw, Wrapped >::set_has_value(), and GU::OptionalCoordinate< Raw, Wrapped >::set_value().
OptionalCoordinate() [3/7]
template<class Raw , class Wrapped > GU::OptionalCoordinate< Raw, Wrapped >::OptionalCoordinate (const bool t_has_value, const Wrapped t_value) inline
Definition at line 79 of file OptionalCoordinate.hpp.
References GU::OptionalCoordinate< Raw, Wrapped >::set_has_value(), and GU::OptionalCoordinate< Raw, Wrapped >::set_value().
OptionalCoordinate() [4/7]
template<class Raw , class Wrapped > GU::OptionalCoordinate< Raw, Wrapped >::OptionalCoordinate (const OptionalCoordinate< Raw, Wrapped > & other) inline
Definition at line 85 of file OptionalCoordinate.hpp.
References GU::OptionalCoordinate< Raw, Wrapped >::set_has_value(), and GU::OptionalCoordinate< Raw, Wrapped >::set_value().
OptionalCoordinate() [5/7]
template<class Raw , class Wrapped > GU::OptionalCoordinate< Raw, Wrapped >::OptionalCoordinate (const Raw & other) inline
Definition at line 91 of file OptionalCoordinate.hpp.
References GU::OptionalCoordinate< Raw, Wrapped >::set_has_value(), and GU::OptionalCoordinate< Raw, Wrapped >::set_value().
OptionalCoordinate() [6/7]
template<class Raw , class Wrapped > GU::OptionalCoordinate< Raw, Wrapped >::OptionalCoordinate (const std::optional< Wrapped > & other) inline
Definition at line 98 of file OptionalCoordinate.hpp.
References GU::OptionalCoordinate< Raw, Wrapped >::set_has_value(), and GU::OptionalCoordinate< Raw, Wrapped >::set_value().
OptionalCoordinate() [7/7]
template<class Raw , class Wrapped > GU::OptionalCoordinate< Raw, Wrapped >::OptionalCoordinate (OptionalCoordinate< Raw, Wrapped > && other) inline
Definition at line 113 of file OptionalCoordinate.hpp.
References GU::OptionalCoordinate< Raw, Wrapped >::set_has_value(), and GU::OptionalCoordinate< Raw, Wrapped >::set_value().
~OptionalCoordinate()
template<class Raw , class Wrapped > GU::OptionalCoordinate< Raw, Wrapped >::~OptionalCoordinate () inline
Definition at line 123 of file OptionalCoordinate.hpp.
Member Function Documentation
asOptional()
template<class Raw , class Wrapped > std::optional< Wrapped > GU::OptionalCoordinate< Raw, Wrapped >::asOptional () const inline
Definition at line 200 of file OptionalCoordinate.hpp.
References GU::OptionalCoordinate< Raw, Wrapped >::has_value(), and GU::OptionalCoordinate< Raw, Wrapped >::value().
has_value()
template<class Raw , class Wrapped > bool GU::OptionalCoordinate< Raw, Wrapped >::has_value () const inline
Definition at line 179 of file OptionalCoordinate.hpp.
Referenced by GU::OptionalCoordinate< Raw, Wrapped >::asOptional(), CGTEST::GUCoordinatesTests< Class >::equals(), and CGTEST::GUCoordinatesTests< Class >::nequals().
operator=() [1/4]
template<class Raw , class Wrapped > OptionalCoordinate< Raw, Wrapped > & GU::OptionalCoordinate< Raw, Wrapped >::operator= (const OptionalCoordinate< Raw, Wrapped > & other) inline
Definition at line 125 of file OptionalCoordinate.hpp.
References GU::OptionalCoordinate< Raw, Wrapped >::set_has_value(), and GU::OptionalCoordinate< Raw, Wrapped >::set_value().
operator=() [2/4]
template<class Raw , class Wrapped > OptionalCoordinate< Raw, Wrapped > & GU::OptionalCoordinate< Raw, Wrapped >::operator= (const Raw & other) inline
Definition at line 136 of file OptionalCoordinate.hpp.
References GU::OptionalCoordinate< Raw, Wrapped >::set_has_value(), and GU::OptionalCoordinate< Raw, Wrapped >::set_value().
operator=() [3/4]
template<class Raw , class Wrapped > OptionalCoordinate< Raw, Wrapped > & GU::OptionalCoordinate< Raw, Wrapped >::operator= (const std::optional< Wrapped > & other) inline
Definition at line 148 of file OptionalCoordinate.hpp.
References GU::OptionalCoordinate< Raw, Wrapped >::set_has_value(), and GU::OptionalCoordinate< Raw, Wrapped >::set_value().
operator=() [4/4]
template<class Raw , class Wrapped > OptionalCoordinate< Raw, Wrapped > & GU::OptionalCoordinate< Raw, Wrapped >::operator= (OptionalCoordinate< Raw, Wrapped > && other) inline
Definition at line 164 of file OptionalCoordinate.hpp.
References GU::OptionalCoordinate< Raw, Wrapped >::set_has_value(), and GU::OptionalCoordinate< Raw, Wrapped >::set_value().
set_has_value()
template<class Raw , class Wrapped > void GU::OptionalCoordinate< Raw, Wrapped >::set_has_value (const bool newValue) inline
Definition at line 184 of file OptionalCoordinate.hpp.
Referenced by GU::OptionalCoordinate< Raw, Wrapped >::OptionalCoordinate(), and GU::OptionalCoordinate< Raw, Wrapped >::operator=().
set_value()
template<class Raw , class Wrapped > void GU::OptionalCoordinate< Raw, Wrapped >::set_value (const Wrapped newValue) inline
Definition at line 194 of file OptionalCoordinate.hpp.
Referenced by GU::OptionalCoordinate< Raw, Wrapped >::OptionalCoordinate(), and GU::OptionalCoordinate< Raw, Wrapped >::operator=().
value()
template<class Raw , class Wrapped > Wrapped GU::OptionalCoordinate< Raw, Wrapped >::value () const inline
Definition at line 189 of file OptionalCoordinate.hpp.
Referenced by GU::OptionalCoordinate< Raw, Wrapped >::asOptional(), CGTEST::GUCoordinatesTests< Class >::equals(), and CGTEST::GUCoordinatesTests< Class >::nequals().
The documentation for this struct was generated from the following file:
OptionalCoordinate.hpp